
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PackingItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PackingItem
 * 
 */
export type PackingItemModel = runtime.Types.Result.DefaultSelection<Prisma.$PackingItemPayload>

export type AggregatePackingItem = {
  _count: PackingItemCountAggregateOutputType | null
  _min: PackingItemMinAggregateOutputType | null
  _max: PackingItemMaxAggregateOutputType | null
}

export type PackingItemMinAggregateOutputType = {
  id: string | null
  name: string | null
  category: string | null
  isChecked: boolean | null
  tripId: string | null
}

export type PackingItemMaxAggregateOutputType = {
  id: string | null
  name: string | null
  category: string | null
  isChecked: boolean | null
  tripId: string | null
}

export type PackingItemCountAggregateOutputType = {
  id: number
  name: number
  category: number
  isChecked: number
  tripId: number
  _all: number
}


export type PackingItemMinAggregateInputType = {
  id?: true
  name?: true
  category?: true
  isChecked?: true
  tripId?: true
}

export type PackingItemMaxAggregateInputType = {
  id?: true
  name?: true
  category?: true
  isChecked?: true
  tripId?: true
}

export type PackingItemCountAggregateInputType = {
  id?: true
  name?: true
  category?: true
  isChecked?: true
  tripId?: true
  _all?: true
}

export type PackingItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PackingItem to aggregate.
   */
  where?: Prisma.PackingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackingItems to fetch.
   */
  orderBy?: Prisma.PackingItemOrderByWithRelationInput | Prisma.PackingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PackingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PackingItems
  **/
  _count?: true | PackingItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PackingItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PackingItemMaxAggregateInputType
}

export type GetPackingItemAggregateType<T extends PackingItemAggregateArgs> = {
      [P in keyof T & keyof AggregatePackingItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePackingItem[P]>
    : Prisma.GetScalarType<T[P], AggregatePackingItem[P]>
}




export type PackingItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PackingItemWhereInput
  orderBy?: Prisma.PackingItemOrderByWithAggregationInput | Prisma.PackingItemOrderByWithAggregationInput[]
  by: Prisma.PackingItemScalarFieldEnum[] | Prisma.PackingItemScalarFieldEnum
  having?: Prisma.PackingItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PackingItemCountAggregateInputType | true
  _min?: PackingItemMinAggregateInputType
  _max?: PackingItemMaxAggregateInputType
}

export type PackingItemGroupByOutputType = {
  id: string
  name: string
  category: string
  isChecked: boolean
  tripId: string
  _count: PackingItemCountAggregateOutputType | null
  _min: PackingItemMinAggregateOutputType | null
  _max: PackingItemMaxAggregateOutputType | null
}

export type GetPackingItemGroupByPayload<T extends PackingItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PackingItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PackingItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PackingItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PackingItemGroupByOutputType[P]>
      }
    >
  >



export type PackingItemWhereInput = {
  AND?: Prisma.PackingItemWhereInput | Prisma.PackingItemWhereInput[]
  OR?: Prisma.PackingItemWhereInput[]
  NOT?: Prisma.PackingItemWhereInput | Prisma.PackingItemWhereInput[]
  id?: Prisma.StringFilter<"PackingItem"> | string
  name?: Prisma.StringFilter<"PackingItem"> | string
  category?: Prisma.StringFilter<"PackingItem"> | string
  isChecked?: Prisma.BoolFilter<"PackingItem"> | boolean
  tripId?: Prisma.StringFilter<"PackingItem"> | string
  trip?: Prisma.XOR<Prisma.TripScalarRelationFilter, Prisma.TripWhereInput>
}

export type PackingItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isChecked?: Prisma.SortOrder
  tripId?: Prisma.SortOrder
  trip?: Prisma.TripOrderByWithRelationInput
}

export type PackingItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PackingItemWhereInput | Prisma.PackingItemWhereInput[]
  OR?: Prisma.PackingItemWhereInput[]
  NOT?: Prisma.PackingItemWhereInput | Prisma.PackingItemWhereInput[]
  name?: Prisma.StringFilter<"PackingItem"> | string
  category?: Prisma.StringFilter<"PackingItem"> | string
  isChecked?: Prisma.BoolFilter<"PackingItem"> | boolean
  tripId?: Prisma.StringFilter<"PackingItem"> | string
  trip?: Prisma.XOR<Prisma.TripScalarRelationFilter, Prisma.TripWhereInput>
}, "id">

export type PackingItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isChecked?: Prisma.SortOrder
  tripId?: Prisma.SortOrder
  _count?: Prisma.PackingItemCountOrderByAggregateInput
  _max?: Prisma.PackingItemMaxOrderByAggregateInput
  _min?: Prisma.PackingItemMinOrderByAggregateInput
}

export type PackingItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.PackingItemScalarWhereWithAggregatesInput | Prisma.PackingItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.PackingItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PackingItemScalarWhereWithAggregatesInput | Prisma.PackingItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PackingItem"> | string
  name?: Prisma.StringWithAggregatesFilter<"PackingItem"> | string
  category?: Prisma.StringWithAggregatesFilter<"PackingItem"> | string
  isChecked?: Prisma.BoolWithAggregatesFilter<"PackingItem"> | boolean
  tripId?: Prisma.StringWithAggregatesFilter<"PackingItem"> | string
}

export type PackingItemCreateInput = {
  id?: string
  name: string
  category: string
  isChecked?: boolean
  trip: Prisma.TripCreateNestedOneWithoutPackingItemsInput
}

export type PackingItemUncheckedCreateInput = {
  id?: string
  name: string
  category: string
  isChecked?: boolean
  tripId: string
}

export type PackingItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isChecked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  trip?: Prisma.TripUpdateOneRequiredWithoutPackingItemsNestedInput
}

export type PackingItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isChecked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tripId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PackingItemCreateManyInput = {
  id?: string
  name: string
  category: string
  isChecked?: boolean
  tripId: string
}

export type PackingItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isChecked?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type PackingItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isChecked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tripId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PackingItemListRelationFilter = {
  every?: Prisma.PackingItemWhereInput
  some?: Prisma.PackingItemWhereInput
  none?: Prisma.PackingItemWhereInput
}

export type PackingItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PackingItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isChecked?: Prisma.SortOrder
  tripId?: Prisma.SortOrder
}

export type PackingItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isChecked?: Prisma.SortOrder
  tripId?: Prisma.SortOrder
}

export type PackingItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isChecked?: Prisma.SortOrder
  tripId?: Prisma.SortOrder
}

export type PackingItemCreateNestedManyWithoutTripInput = {
  create?: Prisma.XOR<Prisma.PackingItemCreateWithoutTripInput, Prisma.PackingItemUncheckedCreateWithoutTripInput> | Prisma.PackingItemCreateWithoutTripInput[] | Prisma.PackingItemUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.PackingItemCreateOrConnectWithoutTripInput | Prisma.PackingItemCreateOrConnectWithoutTripInput[]
  createMany?: Prisma.PackingItemCreateManyTripInputEnvelope
  connect?: Prisma.PackingItemWhereUniqueInput | Prisma.PackingItemWhereUniqueInput[]
}

export type PackingItemUncheckedCreateNestedManyWithoutTripInput = {
  create?: Prisma.XOR<Prisma.PackingItemCreateWithoutTripInput, Prisma.PackingItemUncheckedCreateWithoutTripInput> | Prisma.PackingItemCreateWithoutTripInput[] | Prisma.PackingItemUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.PackingItemCreateOrConnectWithoutTripInput | Prisma.PackingItemCreateOrConnectWithoutTripInput[]
  createMany?: Prisma.PackingItemCreateManyTripInputEnvelope
  connect?: Prisma.PackingItemWhereUniqueInput | Prisma.PackingItemWhereUniqueInput[]
}

export type PackingItemUpdateManyWithoutTripNestedInput = {
  create?: Prisma.XOR<Prisma.PackingItemCreateWithoutTripInput, Prisma.PackingItemUncheckedCreateWithoutTripInput> | Prisma.PackingItemCreateWithoutTripInput[] | Prisma.PackingItemUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.PackingItemCreateOrConnectWithoutTripInput | Prisma.PackingItemCreateOrConnectWithoutTripInput[]
  upsert?: Prisma.PackingItemUpsertWithWhereUniqueWithoutTripInput | Prisma.PackingItemUpsertWithWhereUniqueWithoutTripInput[]
  createMany?: Prisma.PackingItemCreateManyTripInputEnvelope
  set?: Prisma.PackingItemWhereUniqueInput | Prisma.PackingItemWhereUniqueInput[]
  disconnect?: Prisma.PackingItemWhereUniqueInput | Prisma.PackingItemWhereUniqueInput[]
  delete?: Prisma.PackingItemWhereUniqueInput | Prisma.PackingItemWhereUniqueInput[]
  connect?: Prisma.PackingItemWhereUniqueInput | Prisma.PackingItemWhereUniqueInput[]
  update?: Prisma.PackingItemUpdateWithWhereUniqueWithoutTripInput | Prisma.PackingItemUpdateWithWhereUniqueWithoutTripInput[]
  updateMany?: Prisma.PackingItemUpdateManyWithWhereWithoutTripInput | Prisma.PackingItemUpdateManyWithWhereWithoutTripInput[]
  deleteMany?: Prisma.PackingItemScalarWhereInput | Prisma.PackingItemScalarWhereInput[]
}

export type PackingItemUncheckedUpdateManyWithoutTripNestedInput = {
  create?: Prisma.XOR<Prisma.PackingItemCreateWithoutTripInput, Prisma.PackingItemUncheckedCreateWithoutTripInput> | Prisma.PackingItemCreateWithoutTripInput[] | Prisma.PackingItemUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.PackingItemCreateOrConnectWithoutTripInput | Prisma.PackingItemCreateOrConnectWithoutTripInput[]
  upsert?: Prisma.PackingItemUpsertWithWhereUniqueWithoutTripInput | Prisma.PackingItemUpsertWithWhereUniqueWithoutTripInput[]
  createMany?: Prisma.PackingItemCreateManyTripInputEnvelope
  set?: Prisma.PackingItemWhereUniqueInput | Prisma.PackingItemWhereUniqueInput[]
  disconnect?: Prisma.PackingItemWhereUniqueInput | Prisma.PackingItemWhereUniqueInput[]
  delete?: Prisma.PackingItemWhereUniqueInput | Prisma.PackingItemWhereUniqueInput[]
  connect?: Prisma.PackingItemWhereUniqueInput | Prisma.PackingItemWhereUniqueInput[]
  update?: Prisma.PackingItemUpdateWithWhereUniqueWithoutTripInput | Prisma.PackingItemUpdateWithWhereUniqueWithoutTripInput[]
  updateMany?: Prisma.PackingItemUpdateManyWithWhereWithoutTripInput | Prisma.PackingItemUpdateManyWithWhereWithoutTripInput[]
  deleteMany?: Prisma.PackingItemScalarWhereInput | Prisma.PackingItemScalarWhereInput[]
}

export type PackingItemCreateWithoutTripInput = {
  id?: string
  name: string
  category: string
  isChecked?: boolean
}

export type PackingItemUncheckedCreateWithoutTripInput = {
  id?: string
  name: string
  category: string
  isChecked?: boolean
}

export type PackingItemCreateOrConnectWithoutTripInput = {
  where: Prisma.PackingItemWhereUniqueInput
  create: Prisma.XOR<Prisma.PackingItemCreateWithoutTripInput, Prisma.PackingItemUncheckedCreateWithoutTripInput>
}

export type PackingItemCreateManyTripInputEnvelope = {
  data: Prisma.PackingItemCreateManyTripInput | Prisma.PackingItemCreateManyTripInput[]
  skipDuplicates?: boolean
}

export type PackingItemUpsertWithWhereUniqueWithoutTripInput = {
  where: Prisma.PackingItemWhereUniqueInput
  update: Prisma.XOR<Prisma.PackingItemUpdateWithoutTripInput, Prisma.PackingItemUncheckedUpdateWithoutTripInput>
  create: Prisma.XOR<Prisma.PackingItemCreateWithoutTripInput, Prisma.PackingItemUncheckedCreateWithoutTripInput>
}

export type PackingItemUpdateWithWhereUniqueWithoutTripInput = {
  where: Prisma.PackingItemWhereUniqueInput
  data: Prisma.XOR<Prisma.PackingItemUpdateWithoutTripInput, Prisma.PackingItemUncheckedUpdateWithoutTripInput>
}

export type PackingItemUpdateManyWithWhereWithoutTripInput = {
  where: Prisma.PackingItemScalarWhereInput
  data: Prisma.XOR<Prisma.PackingItemUpdateManyMutationInput, Prisma.PackingItemUncheckedUpdateManyWithoutTripInput>
}

export type PackingItemScalarWhereInput = {
  AND?: Prisma.PackingItemScalarWhereInput | Prisma.PackingItemScalarWhereInput[]
  OR?: Prisma.PackingItemScalarWhereInput[]
  NOT?: Prisma.PackingItemScalarWhereInput | Prisma.PackingItemScalarWhereInput[]
  id?: Prisma.StringFilter<"PackingItem"> | string
  name?: Prisma.StringFilter<"PackingItem"> | string
  category?: Prisma.StringFilter<"PackingItem"> | string
  isChecked?: Prisma.BoolFilter<"PackingItem"> | boolean
  tripId?: Prisma.StringFilter<"PackingItem"> | string
}

export type PackingItemCreateManyTripInput = {
  id?: string
  name: string
  category: string
  isChecked?: boolean
}

export type PackingItemUpdateWithoutTripInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isChecked?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type PackingItemUncheckedUpdateWithoutTripInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isChecked?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type PackingItemUncheckedUpdateManyWithoutTripInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isChecked?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type PackingItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  category?: boolean
  isChecked?: boolean
  tripId?: boolean
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}, ExtArgs["result"]["packingItem"]>

export type PackingItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  category?: boolean
  isChecked?: boolean
  tripId?: boolean
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}, ExtArgs["result"]["packingItem"]>

export type PackingItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  category?: boolean
  isChecked?: boolean
  tripId?: boolean
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}, ExtArgs["result"]["packingItem"]>

export type PackingItemSelectScalar = {
  id?: boolean
  name?: boolean
  category?: boolean
  isChecked?: boolean
  tripId?: boolean
}

export type PackingItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "category" | "isChecked" | "tripId", ExtArgs["result"]["packingItem"]>
export type PackingItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}
export type PackingItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}
export type PackingItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}

export type $PackingItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PackingItem"
  objects: {
    trip: Prisma.$TripPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    category: string
    isChecked: boolean
    tripId: string
  }, ExtArgs["result"]["packingItem"]>
  composites: {}
}

export type PackingItemGetPayload<S extends boolean | null | undefined | PackingItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PackingItemPayload, S>

export type PackingItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PackingItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PackingItemCountAggregateInputType | true
  }

export interface PackingItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PackingItem'], meta: { name: 'PackingItem' } }
  /**
   * Find zero or one PackingItem that matches the filter.
   * @param {PackingItemFindUniqueArgs} args - Arguments to find a PackingItem
   * @example
   * // Get one PackingItem
   * const packingItem = await prisma.packingItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PackingItemFindUniqueArgs>(args: Prisma.SelectSubset<T, PackingItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PackingItemClient<runtime.Types.Result.GetResult<Prisma.$PackingItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PackingItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PackingItemFindUniqueOrThrowArgs} args - Arguments to find a PackingItem
   * @example
   * // Get one PackingItem
   * const packingItem = await prisma.packingItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PackingItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PackingItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PackingItemClient<runtime.Types.Result.GetResult<Prisma.$PackingItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PackingItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackingItemFindFirstArgs} args - Arguments to find a PackingItem
   * @example
   * // Get one PackingItem
   * const packingItem = await prisma.packingItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PackingItemFindFirstArgs>(args?: Prisma.SelectSubset<T, PackingItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__PackingItemClient<runtime.Types.Result.GetResult<Prisma.$PackingItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PackingItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackingItemFindFirstOrThrowArgs} args - Arguments to find a PackingItem
   * @example
   * // Get one PackingItem
   * const packingItem = await prisma.packingItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PackingItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PackingItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PackingItemClient<runtime.Types.Result.GetResult<Prisma.$PackingItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PackingItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackingItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PackingItems
   * const packingItems = await prisma.packingItem.findMany()
   * 
   * // Get first 10 PackingItems
   * const packingItems = await prisma.packingItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const packingItemWithIdOnly = await prisma.packingItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PackingItemFindManyArgs>(args?: Prisma.SelectSubset<T, PackingItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackingItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PackingItem.
   * @param {PackingItemCreateArgs} args - Arguments to create a PackingItem.
   * @example
   * // Create one PackingItem
   * const PackingItem = await prisma.packingItem.create({
   *   data: {
   *     // ... data to create a PackingItem
   *   }
   * })
   * 
   */
  create<T extends PackingItemCreateArgs>(args: Prisma.SelectSubset<T, PackingItemCreateArgs<ExtArgs>>): Prisma.Prisma__PackingItemClient<runtime.Types.Result.GetResult<Prisma.$PackingItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PackingItems.
   * @param {PackingItemCreateManyArgs} args - Arguments to create many PackingItems.
   * @example
   * // Create many PackingItems
   * const packingItem = await prisma.packingItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PackingItemCreateManyArgs>(args?: Prisma.SelectSubset<T, PackingItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PackingItems and returns the data saved in the database.
   * @param {PackingItemCreateManyAndReturnArgs} args - Arguments to create many PackingItems.
   * @example
   * // Create many PackingItems
   * const packingItem = await prisma.packingItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PackingItems and only return the `id`
   * const packingItemWithIdOnly = await prisma.packingItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PackingItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PackingItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackingItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PackingItem.
   * @param {PackingItemDeleteArgs} args - Arguments to delete one PackingItem.
   * @example
   * // Delete one PackingItem
   * const PackingItem = await prisma.packingItem.delete({
   *   where: {
   *     // ... filter to delete one PackingItem
   *   }
   * })
   * 
   */
  delete<T extends PackingItemDeleteArgs>(args: Prisma.SelectSubset<T, PackingItemDeleteArgs<ExtArgs>>): Prisma.Prisma__PackingItemClient<runtime.Types.Result.GetResult<Prisma.$PackingItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PackingItem.
   * @param {PackingItemUpdateArgs} args - Arguments to update one PackingItem.
   * @example
   * // Update one PackingItem
   * const packingItem = await prisma.packingItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PackingItemUpdateArgs>(args: Prisma.SelectSubset<T, PackingItemUpdateArgs<ExtArgs>>): Prisma.Prisma__PackingItemClient<runtime.Types.Result.GetResult<Prisma.$PackingItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PackingItems.
   * @param {PackingItemDeleteManyArgs} args - Arguments to filter PackingItems to delete.
   * @example
   * // Delete a few PackingItems
   * const { count } = await prisma.packingItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PackingItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, PackingItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PackingItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackingItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PackingItems
   * const packingItem = await prisma.packingItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PackingItemUpdateManyArgs>(args: Prisma.SelectSubset<T, PackingItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PackingItems and returns the data updated in the database.
   * @param {PackingItemUpdateManyAndReturnArgs} args - Arguments to update many PackingItems.
   * @example
   * // Update many PackingItems
   * const packingItem = await prisma.packingItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PackingItems and only return the `id`
   * const packingItemWithIdOnly = await prisma.packingItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PackingItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PackingItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackingItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PackingItem.
   * @param {PackingItemUpsertArgs} args - Arguments to update or create a PackingItem.
   * @example
   * // Update or create a PackingItem
   * const packingItem = await prisma.packingItem.upsert({
   *   create: {
   *     // ... data to create a PackingItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PackingItem we want to update
   *   }
   * })
   */
  upsert<T extends PackingItemUpsertArgs>(args: Prisma.SelectSubset<T, PackingItemUpsertArgs<ExtArgs>>): Prisma.Prisma__PackingItemClient<runtime.Types.Result.GetResult<Prisma.$PackingItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PackingItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackingItemCountArgs} args - Arguments to filter PackingItems to count.
   * @example
   * // Count the number of PackingItems
   * const count = await prisma.packingItem.count({
   *   where: {
   *     // ... the filter for the PackingItems we want to count
   *   }
   * })
  **/
  count<T extends PackingItemCountArgs>(
    args?: Prisma.Subset<T, PackingItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PackingItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PackingItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackingItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PackingItemAggregateArgs>(args: Prisma.Subset<T, PackingItemAggregateArgs>): Prisma.PrismaPromise<GetPackingItemAggregateType<T>>

  /**
   * Group by PackingItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackingItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PackingItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PackingItemGroupByArgs['orderBy'] }
      : { orderBy?: PackingItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PackingItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPackingItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PackingItem model
 */
readonly fields: PackingItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PackingItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PackingItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  trip<T extends Prisma.TripDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TripDefaultArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PackingItem model
 */
export interface PackingItemFieldRefs {
  readonly id: Prisma.FieldRef<"PackingItem", 'String'>
  readonly name: Prisma.FieldRef<"PackingItem", 'String'>
  readonly category: Prisma.FieldRef<"PackingItem", 'String'>
  readonly isChecked: Prisma.FieldRef<"PackingItem", 'Boolean'>
  readonly tripId: Prisma.FieldRef<"PackingItem", 'String'>
}
    

// Custom InputTypes
/**
 * PackingItem findUnique
 */
export type PackingItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemInclude<ExtArgs> | null
  /**
   * Filter, which PackingItem to fetch.
   */
  where: Prisma.PackingItemWhereUniqueInput
}

/**
 * PackingItem findUniqueOrThrow
 */
export type PackingItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemInclude<ExtArgs> | null
  /**
   * Filter, which PackingItem to fetch.
   */
  where: Prisma.PackingItemWhereUniqueInput
}

/**
 * PackingItem findFirst
 */
export type PackingItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemInclude<ExtArgs> | null
  /**
   * Filter, which PackingItem to fetch.
   */
  where?: Prisma.PackingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackingItems to fetch.
   */
  orderBy?: Prisma.PackingItemOrderByWithRelationInput | Prisma.PackingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PackingItems.
   */
  cursor?: Prisma.PackingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PackingItems.
   */
  distinct?: Prisma.PackingItemScalarFieldEnum | Prisma.PackingItemScalarFieldEnum[]
}

/**
 * PackingItem findFirstOrThrow
 */
export type PackingItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemInclude<ExtArgs> | null
  /**
   * Filter, which PackingItem to fetch.
   */
  where?: Prisma.PackingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackingItems to fetch.
   */
  orderBy?: Prisma.PackingItemOrderByWithRelationInput | Prisma.PackingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PackingItems.
   */
  cursor?: Prisma.PackingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PackingItems.
   */
  distinct?: Prisma.PackingItemScalarFieldEnum | Prisma.PackingItemScalarFieldEnum[]
}

/**
 * PackingItem findMany
 */
export type PackingItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemInclude<ExtArgs> | null
  /**
   * Filter, which PackingItems to fetch.
   */
  where?: Prisma.PackingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackingItems to fetch.
   */
  orderBy?: Prisma.PackingItemOrderByWithRelationInput | Prisma.PackingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PackingItems.
   */
  cursor?: Prisma.PackingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PackingItems.
   */
  distinct?: Prisma.PackingItemScalarFieldEnum | Prisma.PackingItemScalarFieldEnum[]
}

/**
 * PackingItem create
 */
export type PackingItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemInclude<ExtArgs> | null
  /**
   * The data needed to create a PackingItem.
   */
  data: Prisma.XOR<Prisma.PackingItemCreateInput, Prisma.PackingItemUncheckedCreateInput>
}

/**
 * PackingItem createMany
 */
export type PackingItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PackingItems.
   */
  data: Prisma.PackingItemCreateManyInput | Prisma.PackingItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PackingItem createManyAndReturn
 */
export type PackingItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * The data used to create many PackingItems.
   */
  data: Prisma.PackingItemCreateManyInput | Prisma.PackingItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PackingItem update
 */
export type PackingItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemInclude<ExtArgs> | null
  /**
   * The data needed to update a PackingItem.
   */
  data: Prisma.XOR<Prisma.PackingItemUpdateInput, Prisma.PackingItemUncheckedUpdateInput>
  /**
   * Choose, which PackingItem to update.
   */
  where: Prisma.PackingItemWhereUniqueInput
}

/**
 * PackingItem updateMany
 */
export type PackingItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PackingItems.
   */
  data: Prisma.XOR<Prisma.PackingItemUpdateManyMutationInput, Prisma.PackingItemUncheckedUpdateManyInput>
  /**
   * Filter which PackingItems to update
   */
  where?: Prisma.PackingItemWhereInput
  /**
   * Limit how many PackingItems to update.
   */
  limit?: number
}

/**
 * PackingItem updateManyAndReturn
 */
export type PackingItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * The data used to update PackingItems.
   */
  data: Prisma.XOR<Prisma.PackingItemUpdateManyMutationInput, Prisma.PackingItemUncheckedUpdateManyInput>
  /**
   * Filter which PackingItems to update
   */
  where?: Prisma.PackingItemWhereInput
  /**
   * Limit how many PackingItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PackingItem upsert
 */
export type PackingItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemInclude<ExtArgs> | null
  /**
   * The filter to search for the PackingItem to update in case it exists.
   */
  where: Prisma.PackingItemWhereUniqueInput
  /**
   * In case the PackingItem found by the `where` argument doesn't exist, create a new PackingItem with this data.
   */
  create: Prisma.XOR<Prisma.PackingItemCreateInput, Prisma.PackingItemUncheckedCreateInput>
  /**
   * In case the PackingItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PackingItemUpdateInput, Prisma.PackingItemUncheckedUpdateInput>
}

/**
 * PackingItem delete
 */
export type PackingItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemInclude<ExtArgs> | null
  /**
   * Filter which PackingItem to delete.
   */
  where: Prisma.PackingItemWhereUniqueInput
}

/**
 * PackingItem deleteMany
 */
export type PackingItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PackingItems to delete
   */
  where?: Prisma.PackingItemWhereInput
  /**
   * Limit how many PackingItems to delete.
   */
  limit?: number
}

/**
 * PackingItem without action
 */
export type PackingItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemInclude<ExtArgs> | null
}
