
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Stop` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Stop
 * 
 */
export type StopModel = runtime.Types.Result.DefaultSelection<Prisma.$StopPayload>

export type AggregateStop = {
  _count: StopCountAggregateOutputType | null
  _avg: StopAvgAggregateOutputType | null
  _sum: StopSumAggregateOutputType | null
  _min: StopMinAggregateOutputType | null
  _max: StopMaxAggregateOutputType | null
}

export type StopAvgAggregateOutputType = {
  order: number | null
}

export type StopSumAggregateOutputType = {
  order: number | null
}

export type StopMinAggregateOutputType = {
  id: string | null
  arrivalDate: Date | null
  departureDate: Date | null
  order: number | null
  tripId: string | null
  cityId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StopMaxAggregateOutputType = {
  id: string | null
  arrivalDate: Date | null
  departureDate: Date | null
  order: number | null
  tripId: string | null
  cityId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StopCountAggregateOutputType = {
  id: number
  arrivalDate: number
  departureDate: number
  order: number
  tripId: number
  cityId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type StopAvgAggregateInputType = {
  order?: true
}

export type StopSumAggregateInputType = {
  order?: true
}

export type StopMinAggregateInputType = {
  id?: true
  arrivalDate?: true
  departureDate?: true
  order?: true
  tripId?: true
  cityId?: true
  createdAt?: true
  updatedAt?: true
}

export type StopMaxAggregateInputType = {
  id?: true
  arrivalDate?: true
  departureDate?: true
  order?: true
  tripId?: true
  cityId?: true
  createdAt?: true
  updatedAt?: true
}

export type StopCountAggregateInputType = {
  id?: true
  arrivalDate?: true
  departureDate?: true
  order?: true
  tripId?: true
  cityId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type StopAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Stop to aggregate.
   */
  where?: Prisma.StopWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stops to fetch.
   */
  orderBy?: Prisma.StopOrderByWithRelationInput | Prisma.StopOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StopWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stops from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stops.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Stops
  **/
  _count?: true | StopCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StopAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StopSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StopMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StopMaxAggregateInputType
}

export type GetStopAggregateType<T extends StopAggregateArgs> = {
      [P in keyof T & keyof AggregateStop]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStop[P]>
    : Prisma.GetScalarType<T[P], AggregateStop[P]>
}




export type StopGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StopWhereInput
  orderBy?: Prisma.StopOrderByWithAggregationInput | Prisma.StopOrderByWithAggregationInput[]
  by: Prisma.StopScalarFieldEnum[] | Prisma.StopScalarFieldEnum
  having?: Prisma.StopScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StopCountAggregateInputType | true
  _avg?: StopAvgAggregateInputType
  _sum?: StopSumAggregateInputType
  _min?: StopMinAggregateInputType
  _max?: StopMaxAggregateInputType
}

export type StopGroupByOutputType = {
  id: string
  arrivalDate: Date
  departureDate: Date
  order: number
  tripId: string
  cityId: string
  createdAt: Date
  updatedAt: Date
  _count: StopCountAggregateOutputType | null
  _avg: StopAvgAggregateOutputType | null
  _sum: StopSumAggregateOutputType | null
  _min: StopMinAggregateOutputType | null
  _max: StopMaxAggregateOutputType | null
}

export type GetStopGroupByPayload<T extends StopGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StopGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StopGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StopGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StopGroupByOutputType[P]>
      }
    >
  >



export type StopWhereInput = {
  AND?: Prisma.StopWhereInput | Prisma.StopWhereInput[]
  OR?: Prisma.StopWhereInput[]
  NOT?: Prisma.StopWhereInput | Prisma.StopWhereInput[]
  id?: Prisma.StringFilter<"Stop"> | string
  arrivalDate?: Prisma.DateTimeFilter<"Stop"> | Date | string
  departureDate?: Prisma.DateTimeFilter<"Stop"> | Date | string
  order?: Prisma.IntFilter<"Stop"> | number
  tripId?: Prisma.StringFilter<"Stop"> | string
  cityId?: Prisma.StringFilter<"Stop"> | string
  createdAt?: Prisma.DateTimeFilter<"Stop"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Stop"> | Date | string
  trip?: Prisma.XOR<Prisma.TripScalarRelationFilter, Prisma.TripWhereInput>
  city?: Prisma.XOR<Prisma.CityScalarRelationFilter, Prisma.CityWhereInput>
  activities?: Prisma.ActivityListRelationFilter
}

export type StopOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  arrivalDate?: Prisma.SortOrder
  departureDate?: Prisma.SortOrder
  order?: Prisma.SortOrder
  tripId?: Prisma.SortOrder
  cityId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  trip?: Prisma.TripOrderByWithRelationInput
  city?: Prisma.CityOrderByWithRelationInput
  activities?: Prisma.ActivityOrderByRelationAggregateInput
}

export type StopWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.StopWhereInput | Prisma.StopWhereInput[]
  OR?: Prisma.StopWhereInput[]
  NOT?: Prisma.StopWhereInput | Prisma.StopWhereInput[]
  arrivalDate?: Prisma.DateTimeFilter<"Stop"> | Date | string
  departureDate?: Prisma.DateTimeFilter<"Stop"> | Date | string
  order?: Prisma.IntFilter<"Stop"> | number
  tripId?: Prisma.StringFilter<"Stop"> | string
  cityId?: Prisma.StringFilter<"Stop"> | string
  createdAt?: Prisma.DateTimeFilter<"Stop"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Stop"> | Date | string
  trip?: Prisma.XOR<Prisma.TripScalarRelationFilter, Prisma.TripWhereInput>
  city?: Prisma.XOR<Prisma.CityScalarRelationFilter, Prisma.CityWhereInput>
  activities?: Prisma.ActivityListRelationFilter
}, "id">

export type StopOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  arrivalDate?: Prisma.SortOrder
  departureDate?: Prisma.SortOrder
  order?: Prisma.SortOrder
  tripId?: Prisma.SortOrder
  cityId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.StopCountOrderByAggregateInput
  _avg?: Prisma.StopAvgOrderByAggregateInput
  _max?: Prisma.StopMaxOrderByAggregateInput
  _min?: Prisma.StopMinOrderByAggregateInput
  _sum?: Prisma.StopSumOrderByAggregateInput
}

export type StopScalarWhereWithAggregatesInput = {
  AND?: Prisma.StopScalarWhereWithAggregatesInput | Prisma.StopScalarWhereWithAggregatesInput[]
  OR?: Prisma.StopScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StopScalarWhereWithAggregatesInput | Prisma.StopScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Stop"> | string
  arrivalDate?: Prisma.DateTimeWithAggregatesFilter<"Stop"> | Date | string
  departureDate?: Prisma.DateTimeWithAggregatesFilter<"Stop"> | Date | string
  order?: Prisma.IntWithAggregatesFilter<"Stop"> | number
  tripId?: Prisma.StringWithAggregatesFilter<"Stop"> | string
  cityId?: Prisma.StringWithAggregatesFilter<"Stop"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Stop"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Stop"> | Date | string
}

export type StopCreateInput = {
  id?: string
  arrivalDate: Date | string
  departureDate: Date | string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
  trip: Prisma.TripCreateNestedOneWithoutStopsInput
  city: Prisma.CityCreateNestedOneWithoutStopsInput
  activities?: Prisma.ActivityCreateNestedManyWithoutStopInput
}

export type StopUncheckedCreateInput = {
  id?: string
  arrivalDate: Date | string
  departureDate: Date | string
  order: number
  tripId: string
  cityId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  activities?: Prisma.ActivityUncheckedCreateNestedManyWithoutStopInput
}

export type StopUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  arrivalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departureDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  trip?: Prisma.TripUpdateOneRequiredWithoutStopsNestedInput
  city?: Prisma.CityUpdateOneRequiredWithoutStopsNestedInput
  activities?: Prisma.ActivityUpdateManyWithoutStopNestedInput
}

export type StopUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  arrivalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departureDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  tripId?: Prisma.StringFieldUpdateOperationsInput | string
  cityId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  activities?: Prisma.ActivityUncheckedUpdateManyWithoutStopNestedInput
}

export type StopCreateManyInput = {
  id?: string
  arrivalDate: Date | string
  departureDate: Date | string
  order: number
  tripId: string
  cityId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StopUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  arrivalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departureDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StopUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  arrivalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departureDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  tripId?: Prisma.StringFieldUpdateOperationsInput | string
  cityId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StopListRelationFilter = {
  every?: Prisma.StopWhereInput
  some?: Prisma.StopWhereInput
  none?: Prisma.StopWhereInput
}

export type StopOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StopCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  arrivalDate?: Prisma.SortOrder
  departureDate?: Prisma.SortOrder
  order?: Prisma.SortOrder
  tripId?: Prisma.SortOrder
  cityId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StopAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type StopMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  arrivalDate?: Prisma.SortOrder
  departureDate?: Prisma.SortOrder
  order?: Prisma.SortOrder
  tripId?: Prisma.SortOrder
  cityId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StopMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  arrivalDate?: Prisma.SortOrder
  departureDate?: Prisma.SortOrder
  order?: Prisma.SortOrder
  tripId?: Prisma.SortOrder
  cityId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StopSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type StopScalarRelationFilter = {
  is?: Prisma.StopWhereInput
  isNot?: Prisma.StopWhereInput
}

export type StopCreateNestedManyWithoutTripInput = {
  create?: Prisma.XOR<Prisma.StopCreateWithoutTripInput, Prisma.StopUncheckedCreateWithoutTripInput> | Prisma.StopCreateWithoutTripInput[] | Prisma.StopUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.StopCreateOrConnectWithoutTripInput | Prisma.StopCreateOrConnectWithoutTripInput[]
  createMany?: Prisma.StopCreateManyTripInputEnvelope
  connect?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
}

export type StopUncheckedCreateNestedManyWithoutTripInput = {
  create?: Prisma.XOR<Prisma.StopCreateWithoutTripInput, Prisma.StopUncheckedCreateWithoutTripInput> | Prisma.StopCreateWithoutTripInput[] | Prisma.StopUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.StopCreateOrConnectWithoutTripInput | Prisma.StopCreateOrConnectWithoutTripInput[]
  createMany?: Prisma.StopCreateManyTripInputEnvelope
  connect?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
}

export type StopUpdateManyWithoutTripNestedInput = {
  create?: Prisma.XOR<Prisma.StopCreateWithoutTripInput, Prisma.StopUncheckedCreateWithoutTripInput> | Prisma.StopCreateWithoutTripInput[] | Prisma.StopUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.StopCreateOrConnectWithoutTripInput | Prisma.StopCreateOrConnectWithoutTripInput[]
  upsert?: Prisma.StopUpsertWithWhereUniqueWithoutTripInput | Prisma.StopUpsertWithWhereUniqueWithoutTripInput[]
  createMany?: Prisma.StopCreateManyTripInputEnvelope
  set?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  disconnect?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  delete?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  connect?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  update?: Prisma.StopUpdateWithWhereUniqueWithoutTripInput | Prisma.StopUpdateWithWhereUniqueWithoutTripInput[]
  updateMany?: Prisma.StopUpdateManyWithWhereWithoutTripInput | Prisma.StopUpdateManyWithWhereWithoutTripInput[]
  deleteMany?: Prisma.StopScalarWhereInput | Prisma.StopScalarWhereInput[]
}

export type StopUncheckedUpdateManyWithoutTripNestedInput = {
  create?: Prisma.XOR<Prisma.StopCreateWithoutTripInput, Prisma.StopUncheckedCreateWithoutTripInput> | Prisma.StopCreateWithoutTripInput[] | Prisma.StopUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.StopCreateOrConnectWithoutTripInput | Prisma.StopCreateOrConnectWithoutTripInput[]
  upsert?: Prisma.StopUpsertWithWhereUniqueWithoutTripInput | Prisma.StopUpsertWithWhereUniqueWithoutTripInput[]
  createMany?: Prisma.StopCreateManyTripInputEnvelope
  set?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  disconnect?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  delete?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  connect?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  update?: Prisma.StopUpdateWithWhereUniqueWithoutTripInput | Prisma.StopUpdateWithWhereUniqueWithoutTripInput[]
  updateMany?: Prisma.StopUpdateManyWithWhereWithoutTripInput | Prisma.StopUpdateManyWithWhereWithoutTripInput[]
  deleteMany?: Prisma.StopScalarWhereInput | Prisma.StopScalarWhereInput[]
}

export type StopCreateNestedManyWithoutCityInput = {
  create?: Prisma.XOR<Prisma.StopCreateWithoutCityInput, Prisma.StopUncheckedCreateWithoutCityInput> | Prisma.StopCreateWithoutCityInput[] | Prisma.StopUncheckedCreateWithoutCityInput[]
  connectOrCreate?: Prisma.StopCreateOrConnectWithoutCityInput | Prisma.StopCreateOrConnectWithoutCityInput[]
  createMany?: Prisma.StopCreateManyCityInputEnvelope
  connect?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
}

export type StopUncheckedCreateNestedManyWithoutCityInput = {
  create?: Prisma.XOR<Prisma.StopCreateWithoutCityInput, Prisma.StopUncheckedCreateWithoutCityInput> | Prisma.StopCreateWithoutCityInput[] | Prisma.StopUncheckedCreateWithoutCityInput[]
  connectOrCreate?: Prisma.StopCreateOrConnectWithoutCityInput | Prisma.StopCreateOrConnectWithoutCityInput[]
  createMany?: Prisma.StopCreateManyCityInputEnvelope
  connect?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
}

export type StopUpdateManyWithoutCityNestedInput = {
  create?: Prisma.XOR<Prisma.StopCreateWithoutCityInput, Prisma.StopUncheckedCreateWithoutCityInput> | Prisma.StopCreateWithoutCityInput[] | Prisma.StopUncheckedCreateWithoutCityInput[]
  connectOrCreate?: Prisma.StopCreateOrConnectWithoutCityInput | Prisma.StopCreateOrConnectWithoutCityInput[]
  upsert?: Prisma.StopUpsertWithWhereUniqueWithoutCityInput | Prisma.StopUpsertWithWhereUniqueWithoutCityInput[]
  createMany?: Prisma.StopCreateManyCityInputEnvelope
  set?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  disconnect?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  delete?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  connect?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  update?: Prisma.StopUpdateWithWhereUniqueWithoutCityInput | Prisma.StopUpdateWithWhereUniqueWithoutCityInput[]
  updateMany?: Prisma.StopUpdateManyWithWhereWithoutCityInput | Prisma.StopUpdateManyWithWhereWithoutCityInput[]
  deleteMany?: Prisma.StopScalarWhereInput | Prisma.StopScalarWhereInput[]
}

export type StopUncheckedUpdateManyWithoutCityNestedInput = {
  create?: Prisma.XOR<Prisma.StopCreateWithoutCityInput, Prisma.StopUncheckedCreateWithoutCityInput> | Prisma.StopCreateWithoutCityInput[] | Prisma.StopUncheckedCreateWithoutCityInput[]
  connectOrCreate?: Prisma.StopCreateOrConnectWithoutCityInput | Prisma.StopCreateOrConnectWithoutCityInput[]
  upsert?: Prisma.StopUpsertWithWhereUniqueWithoutCityInput | Prisma.StopUpsertWithWhereUniqueWithoutCityInput[]
  createMany?: Prisma.StopCreateManyCityInputEnvelope
  set?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  disconnect?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  delete?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  connect?: Prisma.StopWhereUniqueInput | Prisma.StopWhereUniqueInput[]
  update?: Prisma.StopUpdateWithWhereUniqueWithoutCityInput | Prisma.StopUpdateWithWhereUniqueWithoutCityInput[]
  updateMany?: Prisma.StopUpdateManyWithWhereWithoutCityInput | Prisma.StopUpdateManyWithWhereWithoutCityInput[]
  deleteMany?: Prisma.StopScalarWhereInput | Prisma.StopScalarWhereInput[]
}

export type StopCreateNestedOneWithoutActivitiesInput = {
  create?: Prisma.XOR<Prisma.StopCreateWithoutActivitiesInput, Prisma.StopUncheckedCreateWithoutActivitiesInput>
  connectOrCreate?: Prisma.StopCreateOrConnectWithoutActivitiesInput
  connect?: Prisma.StopWhereUniqueInput
}

export type StopUpdateOneRequiredWithoutActivitiesNestedInput = {
  create?: Prisma.XOR<Prisma.StopCreateWithoutActivitiesInput, Prisma.StopUncheckedCreateWithoutActivitiesInput>
  connectOrCreate?: Prisma.StopCreateOrConnectWithoutActivitiesInput
  upsert?: Prisma.StopUpsertWithoutActivitiesInput
  connect?: Prisma.StopWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StopUpdateToOneWithWhereWithoutActivitiesInput, Prisma.StopUpdateWithoutActivitiesInput>, Prisma.StopUncheckedUpdateWithoutActivitiesInput>
}

export type StopCreateWithoutTripInput = {
  id?: string
  arrivalDate: Date | string
  departureDate: Date | string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
  city: Prisma.CityCreateNestedOneWithoutStopsInput
  activities?: Prisma.ActivityCreateNestedManyWithoutStopInput
}

export type StopUncheckedCreateWithoutTripInput = {
  id?: string
  arrivalDate: Date | string
  departureDate: Date | string
  order: number
  cityId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  activities?: Prisma.ActivityUncheckedCreateNestedManyWithoutStopInput
}

export type StopCreateOrConnectWithoutTripInput = {
  where: Prisma.StopWhereUniqueInput
  create: Prisma.XOR<Prisma.StopCreateWithoutTripInput, Prisma.StopUncheckedCreateWithoutTripInput>
}

export type StopCreateManyTripInputEnvelope = {
  data: Prisma.StopCreateManyTripInput | Prisma.StopCreateManyTripInput[]
  skipDuplicates?: boolean
}

export type StopUpsertWithWhereUniqueWithoutTripInput = {
  where: Prisma.StopWhereUniqueInput
  update: Prisma.XOR<Prisma.StopUpdateWithoutTripInput, Prisma.StopUncheckedUpdateWithoutTripInput>
  create: Prisma.XOR<Prisma.StopCreateWithoutTripInput, Prisma.StopUncheckedCreateWithoutTripInput>
}

export type StopUpdateWithWhereUniqueWithoutTripInput = {
  where: Prisma.StopWhereUniqueInput
  data: Prisma.XOR<Prisma.StopUpdateWithoutTripInput, Prisma.StopUncheckedUpdateWithoutTripInput>
}

export type StopUpdateManyWithWhereWithoutTripInput = {
  where: Prisma.StopScalarWhereInput
  data: Prisma.XOR<Prisma.StopUpdateManyMutationInput, Prisma.StopUncheckedUpdateManyWithoutTripInput>
}

export type StopScalarWhereInput = {
  AND?: Prisma.StopScalarWhereInput | Prisma.StopScalarWhereInput[]
  OR?: Prisma.StopScalarWhereInput[]
  NOT?: Prisma.StopScalarWhereInput | Prisma.StopScalarWhereInput[]
  id?: Prisma.StringFilter<"Stop"> | string
  arrivalDate?: Prisma.DateTimeFilter<"Stop"> | Date | string
  departureDate?: Prisma.DateTimeFilter<"Stop"> | Date | string
  order?: Prisma.IntFilter<"Stop"> | number
  tripId?: Prisma.StringFilter<"Stop"> | string
  cityId?: Prisma.StringFilter<"Stop"> | string
  createdAt?: Prisma.DateTimeFilter<"Stop"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Stop"> | Date | string
}

export type StopCreateWithoutCityInput = {
  id?: string
  arrivalDate: Date | string
  departureDate: Date | string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
  trip: Prisma.TripCreateNestedOneWithoutStopsInput
  activities?: Prisma.ActivityCreateNestedManyWithoutStopInput
}

export type StopUncheckedCreateWithoutCityInput = {
  id?: string
  arrivalDate: Date | string
  departureDate: Date | string
  order: number
  tripId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  activities?: Prisma.ActivityUncheckedCreateNestedManyWithoutStopInput
}

export type StopCreateOrConnectWithoutCityInput = {
  where: Prisma.StopWhereUniqueInput
  create: Prisma.XOR<Prisma.StopCreateWithoutCityInput, Prisma.StopUncheckedCreateWithoutCityInput>
}

export type StopCreateManyCityInputEnvelope = {
  data: Prisma.StopCreateManyCityInput | Prisma.StopCreateManyCityInput[]
  skipDuplicates?: boolean
}

export type StopUpsertWithWhereUniqueWithoutCityInput = {
  where: Prisma.StopWhereUniqueInput
  update: Prisma.XOR<Prisma.StopUpdateWithoutCityInput, Prisma.StopUncheckedUpdateWithoutCityInput>
  create: Prisma.XOR<Prisma.StopCreateWithoutCityInput, Prisma.StopUncheckedCreateWithoutCityInput>
}

export type StopUpdateWithWhereUniqueWithoutCityInput = {
  where: Prisma.StopWhereUniqueInput
  data: Prisma.XOR<Prisma.StopUpdateWithoutCityInput, Prisma.StopUncheckedUpdateWithoutCityInput>
}

export type StopUpdateManyWithWhereWithoutCityInput = {
  where: Prisma.StopScalarWhereInput
  data: Prisma.XOR<Prisma.StopUpdateManyMutationInput, Prisma.StopUncheckedUpdateManyWithoutCityInput>
}

export type StopCreateWithoutActivitiesInput = {
  id?: string
  arrivalDate: Date | string
  departureDate: Date | string
  order: number
  createdAt?: Date | string
  updatedAt?: Date | string
  trip: Prisma.TripCreateNestedOneWithoutStopsInput
  city: Prisma.CityCreateNestedOneWithoutStopsInput
}

export type StopUncheckedCreateWithoutActivitiesInput = {
  id?: string
  arrivalDate: Date | string
  departureDate: Date | string
  order: number
  tripId: string
  cityId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StopCreateOrConnectWithoutActivitiesInput = {
  where: Prisma.StopWhereUniqueInput
  create: Prisma.XOR<Prisma.StopCreateWithoutActivitiesInput, Prisma.StopUncheckedCreateWithoutActivitiesInput>
}

export type StopUpsertWithoutActivitiesInput = {
  update: Prisma.XOR<Prisma.StopUpdateWithoutActivitiesInput, Prisma.StopUncheckedUpdateWithoutActivitiesInput>
  create: Prisma.XOR<Prisma.StopCreateWithoutActivitiesInput, Prisma.StopUncheckedCreateWithoutActivitiesInput>
  where?: Prisma.StopWhereInput
}

export type StopUpdateToOneWithWhereWithoutActivitiesInput = {
  where?: Prisma.StopWhereInput
  data: Prisma.XOR<Prisma.StopUpdateWithoutActivitiesInput, Prisma.StopUncheckedUpdateWithoutActivitiesInput>
}

export type StopUpdateWithoutActivitiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  arrivalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departureDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  trip?: Prisma.TripUpdateOneRequiredWithoutStopsNestedInput
  city?: Prisma.CityUpdateOneRequiredWithoutStopsNestedInput
}

export type StopUncheckedUpdateWithoutActivitiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  arrivalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departureDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  tripId?: Prisma.StringFieldUpdateOperationsInput | string
  cityId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StopCreateManyTripInput = {
  id?: string
  arrivalDate: Date | string
  departureDate: Date | string
  order: number
  cityId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StopUpdateWithoutTripInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  arrivalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departureDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  city?: Prisma.CityUpdateOneRequiredWithoutStopsNestedInput
  activities?: Prisma.ActivityUpdateManyWithoutStopNestedInput
}

export type StopUncheckedUpdateWithoutTripInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  arrivalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departureDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  cityId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  activities?: Prisma.ActivityUncheckedUpdateManyWithoutStopNestedInput
}

export type StopUncheckedUpdateManyWithoutTripInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  arrivalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departureDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  cityId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StopCreateManyCityInput = {
  id?: string
  arrivalDate: Date | string
  departureDate: Date | string
  order: number
  tripId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StopUpdateWithoutCityInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  arrivalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departureDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  trip?: Prisma.TripUpdateOneRequiredWithoutStopsNestedInput
  activities?: Prisma.ActivityUpdateManyWithoutStopNestedInput
}

export type StopUncheckedUpdateWithoutCityInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  arrivalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departureDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  tripId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  activities?: Prisma.ActivityUncheckedUpdateManyWithoutStopNestedInput
}

export type StopUncheckedUpdateManyWithoutCityInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  arrivalDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departureDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  tripId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type StopCountOutputType
 */

export type StopCountOutputType = {
  activities: number
}

export type StopCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  activities?: boolean | StopCountOutputTypeCountActivitiesArgs
}

/**
 * StopCountOutputType without action
 */
export type StopCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StopCountOutputType
   */
  select?: Prisma.StopCountOutputTypeSelect<ExtArgs> | null
}

/**
 * StopCountOutputType without action
 */
export type StopCountOutputTypeCountActivitiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActivityWhereInput
}


export type StopSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  arrivalDate?: boolean
  departureDate?: boolean
  order?: boolean
  tripId?: boolean
  cityId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
  city?: boolean | Prisma.CityDefaultArgs<ExtArgs>
  activities?: boolean | Prisma.Stop$activitiesArgs<ExtArgs>
  _count?: boolean | Prisma.StopCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stop"]>

export type StopSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  arrivalDate?: boolean
  departureDate?: boolean
  order?: boolean
  tripId?: boolean
  cityId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
  city?: boolean | Prisma.CityDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stop"]>

export type StopSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  arrivalDate?: boolean
  departureDate?: boolean
  order?: boolean
  tripId?: boolean
  cityId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
  city?: boolean | Prisma.CityDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stop"]>

export type StopSelectScalar = {
  id?: boolean
  arrivalDate?: boolean
  departureDate?: boolean
  order?: boolean
  tripId?: boolean
  cityId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type StopOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "arrivalDate" | "departureDate" | "order" | "tripId" | "cityId" | "createdAt" | "updatedAt", ExtArgs["result"]["stop"]>
export type StopInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
  city?: boolean | Prisma.CityDefaultArgs<ExtArgs>
  activities?: boolean | Prisma.Stop$activitiesArgs<ExtArgs>
  _count?: boolean | Prisma.StopCountOutputTypeDefaultArgs<ExtArgs>
}
export type StopIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
  city?: boolean | Prisma.CityDefaultArgs<ExtArgs>
}
export type StopIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
  city?: boolean | Prisma.CityDefaultArgs<ExtArgs>
}

export type $StopPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Stop"
  objects: {
    trip: Prisma.$TripPayload<ExtArgs>
    city: Prisma.$CityPayload<ExtArgs>
    activities: Prisma.$ActivityPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    arrivalDate: Date
    departureDate: Date
    order: number
    tripId: string
    cityId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["stop"]>
  composites: {}
}

export type StopGetPayload<S extends boolean | null | undefined | StopDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StopPayload, S>

export type StopCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StopFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StopCountAggregateInputType | true
  }

export interface StopDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Stop'], meta: { name: 'Stop' } }
  /**
   * Find zero or one Stop that matches the filter.
   * @param {StopFindUniqueArgs} args - Arguments to find a Stop
   * @example
   * // Get one Stop
   * const stop = await prisma.stop.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StopFindUniqueArgs>(args: Prisma.SelectSubset<T, StopFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StopClient<runtime.Types.Result.GetResult<Prisma.$StopPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Stop that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StopFindUniqueOrThrowArgs} args - Arguments to find a Stop
   * @example
   * // Get one Stop
   * const stop = await prisma.stop.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StopFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StopFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StopClient<runtime.Types.Result.GetResult<Prisma.$StopPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Stop that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StopFindFirstArgs} args - Arguments to find a Stop
   * @example
   * // Get one Stop
   * const stop = await prisma.stop.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StopFindFirstArgs>(args?: Prisma.SelectSubset<T, StopFindFirstArgs<ExtArgs>>): Prisma.Prisma__StopClient<runtime.Types.Result.GetResult<Prisma.$StopPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Stop that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StopFindFirstOrThrowArgs} args - Arguments to find a Stop
   * @example
   * // Get one Stop
   * const stop = await prisma.stop.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StopFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StopFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StopClient<runtime.Types.Result.GetResult<Prisma.$StopPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Stops that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StopFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Stops
   * const stops = await prisma.stop.findMany()
   * 
   * // Get first 10 Stops
   * const stops = await prisma.stop.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const stopWithIdOnly = await prisma.stop.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StopFindManyArgs>(args?: Prisma.SelectSubset<T, StopFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StopPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Stop.
   * @param {StopCreateArgs} args - Arguments to create a Stop.
   * @example
   * // Create one Stop
   * const Stop = await prisma.stop.create({
   *   data: {
   *     // ... data to create a Stop
   *   }
   * })
   * 
   */
  create<T extends StopCreateArgs>(args: Prisma.SelectSubset<T, StopCreateArgs<ExtArgs>>): Prisma.Prisma__StopClient<runtime.Types.Result.GetResult<Prisma.$StopPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Stops.
   * @param {StopCreateManyArgs} args - Arguments to create many Stops.
   * @example
   * // Create many Stops
   * const stop = await prisma.stop.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StopCreateManyArgs>(args?: Prisma.SelectSubset<T, StopCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Stops and returns the data saved in the database.
   * @param {StopCreateManyAndReturnArgs} args - Arguments to create many Stops.
   * @example
   * // Create many Stops
   * const stop = await prisma.stop.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Stops and only return the `id`
   * const stopWithIdOnly = await prisma.stop.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StopCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StopCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StopPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Stop.
   * @param {StopDeleteArgs} args - Arguments to delete one Stop.
   * @example
   * // Delete one Stop
   * const Stop = await prisma.stop.delete({
   *   where: {
   *     // ... filter to delete one Stop
   *   }
   * })
   * 
   */
  delete<T extends StopDeleteArgs>(args: Prisma.SelectSubset<T, StopDeleteArgs<ExtArgs>>): Prisma.Prisma__StopClient<runtime.Types.Result.GetResult<Prisma.$StopPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Stop.
   * @param {StopUpdateArgs} args - Arguments to update one Stop.
   * @example
   * // Update one Stop
   * const stop = await prisma.stop.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StopUpdateArgs>(args: Prisma.SelectSubset<T, StopUpdateArgs<ExtArgs>>): Prisma.Prisma__StopClient<runtime.Types.Result.GetResult<Prisma.$StopPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Stops.
   * @param {StopDeleteManyArgs} args - Arguments to filter Stops to delete.
   * @example
   * // Delete a few Stops
   * const { count } = await prisma.stop.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StopDeleteManyArgs>(args?: Prisma.SelectSubset<T, StopDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Stops.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StopUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Stops
   * const stop = await prisma.stop.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StopUpdateManyArgs>(args: Prisma.SelectSubset<T, StopUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Stops and returns the data updated in the database.
   * @param {StopUpdateManyAndReturnArgs} args - Arguments to update many Stops.
   * @example
   * // Update many Stops
   * const stop = await prisma.stop.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Stops and only return the `id`
   * const stopWithIdOnly = await prisma.stop.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StopUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StopUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StopPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Stop.
   * @param {StopUpsertArgs} args - Arguments to update or create a Stop.
   * @example
   * // Update or create a Stop
   * const stop = await prisma.stop.upsert({
   *   create: {
   *     // ... data to create a Stop
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Stop we want to update
   *   }
   * })
   */
  upsert<T extends StopUpsertArgs>(args: Prisma.SelectSubset<T, StopUpsertArgs<ExtArgs>>): Prisma.Prisma__StopClient<runtime.Types.Result.GetResult<Prisma.$StopPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Stops.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StopCountArgs} args - Arguments to filter Stops to count.
   * @example
   * // Count the number of Stops
   * const count = await prisma.stop.count({
   *   where: {
   *     // ... the filter for the Stops we want to count
   *   }
   * })
  **/
  count<T extends StopCountArgs>(
    args?: Prisma.Subset<T, StopCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StopCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Stop.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StopAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StopAggregateArgs>(args: Prisma.Subset<T, StopAggregateArgs>): Prisma.PrismaPromise<GetStopAggregateType<T>>

  /**
   * Group by Stop.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StopGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StopGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StopGroupByArgs['orderBy'] }
      : { orderBy?: StopGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StopGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStopGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Stop model
 */
readonly fields: StopFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Stop.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StopClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  trip<T extends Prisma.TripDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TripDefaultArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  city<T extends Prisma.CityDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CityDefaultArgs<ExtArgs>>): Prisma.Prisma__CityClient<runtime.Types.Result.GetResult<Prisma.$CityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  activities<T extends Prisma.Stop$activitiesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Stop$activitiesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActivityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Stop model
 */
export interface StopFieldRefs {
  readonly id: Prisma.FieldRef<"Stop", 'String'>
  readonly arrivalDate: Prisma.FieldRef<"Stop", 'DateTime'>
  readonly departureDate: Prisma.FieldRef<"Stop", 'DateTime'>
  readonly order: Prisma.FieldRef<"Stop", 'Int'>
  readonly tripId: Prisma.FieldRef<"Stop", 'String'>
  readonly cityId: Prisma.FieldRef<"Stop", 'String'>
  readonly createdAt: Prisma.FieldRef<"Stop", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Stop", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Stop findUnique
 */
export type StopFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopInclude<ExtArgs> | null
  /**
   * Filter, which Stop to fetch.
   */
  where: Prisma.StopWhereUniqueInput
}

/**
 * Stop findUniqueOrThrow
 */
export type StopFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopInclude<ExtArgs> | null
  /**
   * Filter, which Stop to fetch.
   */
  where: Prisma.StopWhereUniqueInput
}

/**
 * Stop findFirst
 */
export type StopFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopInclude<ExtArgs> | null
  /**
   * Filter, which Stop to fetch.
   */
  where?: Prisma.StopWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stops to fetch.
   */
  orderBy?: Prisma.StopOrderByWithRelationInput | Prisma.StopOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Stops.
   */
  cursor?: Prisma.StopWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stops from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stops.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Stops.
   */
  distinct?: Prisma.StopScalarFieldEnum | Prisma.StopScalarFieldEnum[]
}

/**
 * Stop findFirstOrThrow
 */
export type StopFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopInclude<ExtArgs> | null
  /**
   * Filter, which Stop to fetch.
   */
  where?: Prisma.StopWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stops to fetch.
   */
  orderBy?: Prisma.StopOrderByWithRelationInput | Prisma.StopOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Stops.
   */
  cursor?: Prisma.StopWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stops from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stops.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Stops.
   */
  distinct?: Prisma.StopScalarFieldEnum | Prisma.StopScalarFieldEnum[]
}

/**
 * Stop findMany
 */
export type StopFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopInclude<ExtArgs> | null
  /**
   * Filter, which Stops to fetch.
   */
  where?: Prisma.StopWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stops to fetch.
   */
  orderBy?: Prisma.StopOrderByWithRelationInput | Prisma.StopOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Stops.
   */
  cursor?: Prisma.StopWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stops from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stops.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Stops.
   */
  distinct?: Prisma.StopScalarFieldEnum | Prisma.StopScalarFieldEnum[]
}

/**
 * Stop create
 */
export type StopCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopInclude<ExtArgs> | null
  /**
   * The data needed to create a Stop.
   */
  data: Prisma.XOR<Prisma.StopCreateInput, Prisma.StopUncheckedCreateInput>
}

/**
 * Stop createMany
 */
export type StopCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Stops.
   */
  data: Prisma.StopCreateManyInput | Prisma.StopCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Stop createManyAndReturn
 */
export type StopCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * The data used to create many Stops.
   */
  data: Prisma.StopCreateManyInput | Prisma.StopCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Stop update
 */
export type StopUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopInclude<ExtArgs> | null
  /**
   * The data needed to update a Stop.
   */
  data: Prisma.XOR<Prisma.StopUpdateInput, Prisma.StopUncheckedUpdateInput>
  /**
   * Choose, which Stop to update.
   */
  where: Prisma.StopWhereUniqueInput
}

/**
 * Stop updateMany
 */
export type StopUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Stops.
   */
  data: Prisma.XOR<Prisma.StopUpdateManyMutationInput, Prisma.StopUncheckedUpdateManyInput>
  /**
   * Filter which Stops to update
   */
  where?: Prisma.StopWhereInput
  /**
   * Limit how many Stops to update.
   */
  limit?: number
}

/**
 * Stop updateManyAndReturn
 */
export type StopUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * The data used to update Stops.
   */
  data: Prisma.XOR<Prisma.StopUpdateManyMutationInput, Prisma.StopUncheckedUpdateManyInput>
  /**
   * Filter which Stops to update
   */
  where?: Prisma.StopWhereInput
  /**
   * Limit how many Stops to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Stop upsert
 */
export type StopUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopInclude<ExtArgs> | null
  /**
   * The filter to search for the Stop to update in case it exists.
   */
  where: Prisma.StopWhereUniqueInput
  /**
   * In case the Stop found by the `where` argument doesn't exist, create a new Stop with this data.
   */
  create: Prisma.XOR<Prisma.StopCreateInput, Prisma.StopUncheckedCreateInput>
  /**
   * In case the Stop was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StopUpdateInput, Prisma.StopUncheckedUpdateInput>
}

/**
 * Stop delete
 */
export type StopDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopInclude<ExtArgs> | null
  /**
   * Filter which Stop to delete.
   */
  where: Prisma.StopWhereUniqueInput
}

/**
 * Stop deleteMany
 */
export type StopDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Stops to delete
   */
  where?: Prisma.StopWhereInput
  /**
   * Limit how many Stops to delete.
   */
  limit?: number
}

/**
 * Stop.activities
 */
export type Stop$activitiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Activity
   */
  select?: Prisma.ActivitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Activity
   */
  omit?: Prisma.ActivityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityInclude<ExtArgs> | null
  where?: Prisma.ActivityWhereInput
  orderBy?: Prisma.ActivityOrderByWithRelationInput | Prisma.ActivityOrderByWithRelationInput[]
  cursor?: Prisma.ActivityWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ActivityScalarFieldEnum | Prisma.ActivityScalarFieldEnum[]
}

/**
 * Stop without action
 */
export type StopDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopInclude<ExtArgs> | null
}
