
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Trip` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Trip
 * 
 */
export type TripModel = runtime.Types.Result.DefaultSelection<Prisma.$TripPayload>

export type AggregateTrip = {
  _count: TripCountAggregateOutputType | null
  _min: TripMinAggregateOutputType | null
  _max: TripMaxAggregateOutputType | null
}

export type TripMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  startDate: Date | null
  endDate: Date | null
  coverPhoto: string | null
  isPublic: boolean | null
  publicId: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TripMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  startDate: Date | null
  endDate: Date | null
  coverPhoto: string | null
  isPublic: boolean | null
  publicId: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TripCountAggregateOutputType = {
  id: number
  name: number
  description: number
  startDate: number
  endDate: number
  coverPhoto: number
  isPublic: number
  publicId: number
  userId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TripMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  startDate?: true
  endDate?: true
  coverPhoto?: true
  isPublic?: true
  publicId?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type TripMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  startDate?: true
  endDate?: true
  coverPhoto?: true
  isPublic?: true
  publicId?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type TripCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  startDate?: true
  endDate?: true
  coverPhoto?: true
  isPublic?: true
  publicId?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TripAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Trip to aggregate.
   */
  where?: Prisma.TripWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Trips to fetch.
   */
  orderBy?: Prisma.TripOrderByWithRelationInput | Prisma.TripOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TripWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Trips from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Trips.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Trips
  **/
  _count?: true | TripCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TripMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TripMaxAggregateInputType
}

export type GetTripAggregateType<T extends TripAggregateArgs> = {
      [P in keyof T & keyof AggregateTrip]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTrip[P]>
    : Prisma.GetScalarType<T[P], AggregateTrip[P]>
}




export type TripGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TripWhereInput
  orderBy?: Prisma.TripOrderByWithAggregationInput | Prisma.TripOrderByWithAggregationInput[]
  by: Prisma.TripScalarFieldEnum[] | Prisma.TripScalarFieldEnum
  having?: Prisma.TripScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TripCountAggregateInputType | true
  _min?: TripMinAggregateInputType
  _max?: TripMaxAggregateInputType
}

export type TripGroupByOutputType = {
  id: string
  name: string
  description: string | null
  startDate: Date
  endDate: Date
  coverPhoto: string | null
  isPublic: boolean
  publicId: string
  userId: string
  createdAt: Date
  updatedAt: Date
  _count: TripCountAggregateOutputType | null
  _min: TripMinAggregateOutputType | null
  _max: TripMaxAggregateOutputType | null
}

export type GetTripGroupByPayload<T extends TripGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TripGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TripGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TripGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TripGroupByOutputType[P]>
      }
    >
  >



export type TripWhereInput = {
  AND?: Prisma.TripWhereInput | Prisma.TripWhereInput[]
  OR?: Prisma.TripWhereInput[]
  NOT?: Prisma.TripWhereInput | Prisma.TripWhereInput[]
  id?: Prisma.StringFilter<"Trip"> | string
  name?: Prisma.StringFilter<"Trip"> | string
  description?: Prisma.StringNullableFilter<"Trip"> | string | null
  startDate?: Prisma.DateTimeFilter<"Trip"> | Date | string
  endDate?: Prisma.DateTimeFilter<"Trip"> | Date | string
  coverPhoto?: Prisma.StringNullableFilter<"Trip"> | string | null
  isPublic?: Prisma.BoolFilter<"Trip"> | boolean
  publicId?: Prisma.StringFilter<"Trip"> | string
  userId?: Prisma.StringFilter<"Trip"> | string
  createdAt?: Prisma.DateTimeFilter<"Trip"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Trip"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  stops?: Prisma.StopListRelationFilter
  budgets?: Prisma.BudgetListRelationFilter
  packingItems?: Prisma.PackingItemListRelationFilter
  notes?: Prisma.NoteListRelationFilter
}

export type TripOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  coverPhoto?: Prisma.SortOrderInput | Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  publicId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  stops?: Prisma.StopOrderByRelationAggregateInput
  budgets?: Prisma.BudgetOrderByRelationAggregateInput
  packingItems?: Prisma.PackingItemOrderByRelationAggregateInput
  notes?: Prisma.NoteOrderByRelationAggregateInput
}

export type TripWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  publicId?: string
  AND?: Prisma.TripWhereInput | Prisma.TripWhereInput[]
  OR?: Prisma.TripWhereInput[]
  NOT?: Prisma.TripWhereInput | Prisma.TripWhereInput[]
  name?: Prisma.StringFilter<"Trip"> | string
  description?: Prisma.StringNullableFilter<"Trip"> | string | null
  startDate?: Prisma.DateTimeFilter<"Trip"> | Date | string
  endDate?: Prisma.DateTimeFilter<"Trip"> | Date | string
  coverPhoto?: Prisma.StringNullableFilter<"Trip"> | string | null
  isPublic?: Prisma.BoolFilter<"Trip"> | boolean
  userId?: Prisma.StringFilter<"Trip"> | string
  createdAt?: Prisma.DateTimeFilter<"Trip"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Trip"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  stops?: Prisma.StopListRelationFilter
  budgets?: Prisma.BudgetListRelationFilter
  packingItems?: Prisma.PackingItemListRelationFilter
  notes?: Prisma.NoteListRelationFilter
}, "id" | "publicId">

export type TripOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  coverPhoto?: Prisma.SortOrderInput | Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  publicId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TripCountOrderByAggregateInput
  _max?: Prisma.TripMaxOrderByAggregateInput
  _min?: Prisma.TripMinOrderByAggregateInput
}

export type TripScalarWhereWithAggregatesInput = {
  AND?: Prisma.TripScalarWhereWithAggregatesInput | Prisma.TripScalarWhereWithAggregatesInput[]
  OR?: Prisma.TripScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TripScalarWhereWithAggregatesInput | Prisma.TripScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Trip"> | string
  name?: Prisma.StringWithAggregatesFilter<"Trip"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Trip"> | string | null
  startDate?: Prisma.DateTimeWithAggregatesFilter<"Trip"> | Date | string
  endDate?: Prisma.DateTimeWithAggregatesFilter<"Trip"> | Date | string
  coverPhoto?: Prisma.StringNullableWithAggregatesFilter<"Trip"> | string | null
  isPublic?: Prisma.BoolWithAggregatesFilter<"Trip"> | boolean
  publicId?: Prisma.StringWithAggregatesFilter<"Trip"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Trip"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Trip"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Trip"> | Date | string
}

export type TripCreateInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTripsInput
  stops?: Prisma.StopCreateNestedManyWithoutTripInput
  budgets?: Prisma.BudgetCreateNestedManyWithoutTripInput
  packingItems?: Prisma.PackingItemCreateNestedManyWithoutTripInput
  notes?: Prisma.NoteCreateNestedManyWithoutTripInput
}

export type TripUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  stops?: Prisma.StopUncheckedCreateNestedManyWithoutTripInput
  budgets?: Prisma.BudgetUncheckedCreateNestedManyWithoutTripInput
  packingItems?: Prisma.PackingItemUncheckedCreateNestedManyWithoutTripInput
  notes?: Prisma.NoteUncheckedCreateNestedManyWithoutTripInput
}

export type TripUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTripsNestedInput
  stops?: Prisma.StopUpdateManyWithoutTripNestedInput
  budgets?: Prisma.BudgetUpdateManyWithoutTripNestedInput
  packingItems?: Prisma.PackingItemUpdateManyWithoutTripNestedInput
  notes?: Prisma.NoteUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stops?: Prisma.StopUncheckedUpdateManyWithoutTripNestedInput
  budgets?: Prisma.BudgetUncheckedUpdateManyWithoutTripNestedInput
  packingItems?: Prisma.PackingItemUncheckedUpdateManyWithoutTripNestedInput
  notes?: Prisma.NoteUncheckedUpdateManyWithoutTripNestedInput
}

export type TripCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TripUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TripUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TripListRelationFilter = {
  every?: Prisma.TripWhereInput
  some?: Prisma.TripWhereInput
  none?: Prisma.TripWhereInput
}

export type TripOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TripCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  coverPhoto?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  publicId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TripMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  coverPhoto?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  publicId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TripMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  coverPhoto?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  publicId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TripScalarRelationFilter = {
  is?: Prisma.TripWhereInput
  isNot?: Prisma.TripWhereInput
}

export type TripCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutUserInput, Prisma.TripUncheckedCreateWithoutUserInput> | Prisma.TripCreateWithoutUserInput[] | Prisma.TripUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutUserInput | Prisma.TripCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TripCreateManyUserInputEnvelope
  connect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
}

export type TripUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutUserInput, Prisma.TripUncheckedCreateWithoutUserInput> | Prisma.TripCreateWithoutUserInput[] | Prisma.TripUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutUserInput | Prisma.TripCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TripCreateManyUserInputEnvelope
  connect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
}

export type TripUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutUserInput, Prisma.TripUncheckedCreateWithoutUserInput> | Prisma.TripCreateWithoutUserInput[] | Prisma.TripUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutUserInput | Prisma.TripCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TripUpsertWithWhereUniqueWithoutUserInput | Prisma.TripUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TripCreateManyUserInputEnvelope
  set?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  disconnect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  delete?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  connect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  update?: Prisma.TripUpdateWithWhereUniqueWithoutUserInput | Prisma.TripUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TripUpdateManyWithWhereWithoutUserInput | Prisma.TripUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TripScalarWhereInput | Prisma.TripScalarWhereInput[]
}

export type TripUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutUserInput, Prisma.TripUncheckedCreateWithoutUserInput> | Prisma.TripCreateWithoutUserInput[] | Prisma.TripUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutUserInput | Prisma.TripCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TripUpsertWithWhereUniqueWithoutUserInput | Prisma.TripUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TripCreateManyUserInputEnvelope
  set?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  disconnect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  delete?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  connect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  update?: Prisma.TripUpdateWithWhereUniqueWithoutUserInput | Prisma.TripUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TripUpdateManyWithWhereWithoutUserInput | Prisma.TripUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TripScalarWhereInput | Prisma.TripScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type TripCreateNestedOneWithoutStopsInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutStopsInput, Prisma.TripUncheckedCreateWithoutStopsInput>
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutStopsInput
  connect?: Prisma.TripWhereUniqueInput
}

export type TripUpdateOneRequiredWithoutStopsNestedInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutStopsInput, Prisma.TripUncheckedCreateWithoutStopsInput>
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutStopsInput
  upsert?: Prisma.TripUpsertWithoutStopsInput
  connect?: Prisma.TripWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TripUpdateToOneWithWhereWithoutStopsInput, Prisma.TripUpdateWithoutStopsInput>, Prisma.TripUncheckedUpdateWithoutStopsInput>
}

export type TripCreateNestedOneWithoutBudgetsInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutBudgetsInput, Prisma.TripUncheckedCreateWithoutBudgetsInput>
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutBudgetsInput
  connect?: Prisma.TripWhereUniqueInput
}

export type TripUpdateOneRequiredWithoutBudgetsNestedInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutBudgetsInput, Prisma.TripUncheckedCreateWithoutBudgetsInput>
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutBudgetsInput
  upsert?: Prisma.TripUpsertWithoutBudgetsInput
  connect?: Prisma.TripWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TripUpdateToOneWithWhereWithoutBudgetsInput, Prisma.TripUpdateWithoutBudgetsInput>, Prisma.TripUncheckedUpdateWithoutBudgetsInput>
}

export type TripCreateNestedOneWithoutPackingItemsInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutPackingItemsInput, Prisma.TripUncheckedCreateWithoutPackingItemsInput>
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutPackingItemsInput
  connect?: Prisma.TripWhereUniqueInput
}

export type TripUpdateOneRequiredWithoutPackingItemsNestedInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutPackingItemsInput, Prisma.TripUncheckedCreateWithoutPackingItemsInput>
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutPackingItemsInput
  upsert?: Prisma.TripUpsertWithoutPackingItemsInput
  connect?: Prisma.TripWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TripUpdateToOneWithWhereWithoutPackingItemsInput, Prisma.TripUpdateWithoutPackingItemsInput>, Prisma.TripUncheckedUpdateWithoutPackingItemsInput>
}

export type TripCreateNestedOneWithoutNotesInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutNotesInput, Prisma.TripUncheckedCreateWithoutNotesInput>
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutNotesInput
  connect?: Prisma.TripWhereUniqueInput
}

export type TripUpdateOneRequiredWithoutNotesNestedInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutNotesInput, Prisma.TripUncheckedCreateWithoutNotesInput>
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutNotesInput
  upsert?: Prisma.TripUpsertWithoutNotesInput
  connect?: Prisma.TripWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TripUpdateToOneWithWhereWithoutNotesInput, Prisma.TripUpdateWithoutNotesInput>, Prisma.TripUncheckedUpdateWithoutNotesInput>
}

export type TripCreateWithoutUserInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  stops?: Prisma.StopCreateNestedManyWithoutTripInput
  budgets?: Prisma.BudgetCreateNestedManyWithoutTripInput
  packingItems?: Prisma.PackingItemCreateNestedManyWithoutTripInput
  notes?: Prisma.NoteCreateNestedManyWithoutTripInput
}

export type TripUncheckedCreateWithoutUserInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  stops?: Prisma.StopUncheckedCreateNestedManyWithoutTripInput
  budgets?: Prisma.BudgetUncheckedCreateNestedManyWithoutTripInput
  packingItems?: Prisma.PackingItemUncheckedCreateNestedManyWithoutTripInput
  notes?: Prisma.NoteUncheckedCreateNestedManyWithoutTripInput
}

export type TripCreateOrConnectWithoutUserInput = {
  where: Prisma.TripWhereUniqueInput
  create: Prisma.XOR<Prisma.TripCreateWithoutUserInput, Prisma.TripUncheckedCreateWithoutUserInput>
}

export type TripCreateManyUserInputEnvelope = {
  data: Prisma.TripCreateManyUserInput | Prisma.TripCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type TripUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TripWhereUniqueInput
  update: Prisma.XOR<Prisma.TripUpdateWithoutUserInput, Prisma.TripUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TripCreateWithoutUserInput, Prisma.TripUncheckedCreateWithoutUserInput>
}

export type TripUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TripWhereUniqueInput
  data: Prisma.XOR<Prisma.TripUpdateWithoutUserInput, Prisma.TripUncheckedUpdateWithoutUserInput>
}

export type TripUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TripScalarWhereInput
  data: Prisma.XOR<Prisma.TripUpdateManyMutationInput, Prisma.TripUncheckedUpdateManyWithoutUserInput>
}

export type TripScalarWhereInput = {
  AND?: Prisma.TripScalarWhereInput | Prisma.TripScalarWhereInput[]
  OR?: Prisma.TripScalarWhereInput[]
  NOT?: Prisma.TripScalarWhereInput | Prisma.TripScalarWhereInput[]
  id?: Prisma.StringFilter<"Trip"> | string
  name?: Prisma.StringFilter<"Trip"> | string
  description?: Prisma.StringNullableFilter<"Trip"> | string | null
  startDate?: Prisma.DateTimeFilter<"Trip"> | Date | string
  endDate?: Prisma.DateTimeFilter<"Trip"> | Date | string
  coverPhoto?: Prisma.StringNullableFilter<"Trip"> | string | null
  isPublic?: Prisma.BoolFilter<"Trip"> | boolean
  publicId?: Prisma.StringFilter<"Trip"> | string
  userId?: Prisma.StringFilter<"Trip"> | string
  createdAt?: Prisma.DateTimeFilter<"Trip"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Trip"> | Date | string
}

export type TripCreateWithoutStopsInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTripsInput
  budgets?: Prisma.BudgetCreateNestedManyWithoutTripInput
  packingItems?: Prisma.PackingItemCreateNestedManyWithoutTripInput
  notes?: Prisma.NoteCreateNestedManyWithoutTripInput
}

export type TripUncheckedCreateWithoutStopsInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  budgets?: Prisma.BudgetUncheckedCreateNestedManyWithoutTripInput
  packingItems?: Prisma.PackingItemUncheckedCreateNestedManyWithoutTripInput
  notes?: Prisma.NoteUncheckedCreateNestedManyWithoutTripInput
}

export type TripCreateOrConnectWithoutStopsInput = {
  where: Prisma.TripWhereUniqueInput
  create: Prisma.XOR<Prisma.TripCreateWithoutStopsInput, Prisma.TripUncheckedCreateWithoutStopsInput>
}

export type TripUpsertWithoutStopsInput = {
  update: Prisma.XOR<Prisma.TripUpdateWithoutStopsInput, Prisma.TripUncheckedUpdateWithoutStopsInput>
  create: Prisma.XOR<Prisma.TripCreateWithoutStopsInput, Prisma.TripUncheckedCreateWithoutStopsInput>
  where?: Prisma.TripWhereInput
}

export type TripUpdateToOneWithWhereWithoutStopsInput = {
  where?: Prisma.TripWhereInput
  data: Prisma.XOR<Prisma.TripUpdateWithoutStopsInput, Prisma.TripUncheckedUpdateWithoutStopsInput>
}

export type TripUpdateWithoutStopsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTripsNestedInput
  budgets?: Prisma.BudgetUpdateManyWithoutTripNestedInput
  packingItems?: Prisma.PackingItemUpdateManyWithoutTripNestedInput
  notes?: Prisma.NoteUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateWithoutStopsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  budgets?: Prisma.BudgetUncheckedUpdateManyWithoutTripNestedInput
  packingItems?: Prisma.PackingItemUncheckedUpdateManyWithoutTripNestedInput
  notes?: Prisma.NoteUncheckedUpdateManyWithoutTripNestedInput
}

export type TripCreateWithoutBudgetsInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTripsInput
  stops?: Prisma.StopCreateNestedManyWithoutTripInput
  packingItems?: Prisma.PackingItemCreateNestedManyWithoutTripInput
  notes?: Prisma.NoteCreateNestedManyWithoutTripInput
}

export type TripUncheckedCreateWithoutBudgetsInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  stops?: Prisma.StopUncheckedCreateNestedManyWithoutTripInput
  packingItems?: Prisma.PackingItemUncheckedCreateNestedManyWithoutTripInput
  notes?: Prisma.NoteUncheckedCreateNestedManyWithoutTripInput
}

export type TripCreateOrConnectWithoutBudgetsInput = {
  where: Prisma.TripWhereUniqueInput
  create: Prisma.XOR<Prisma.TripCreateWithoutBudgetsInput, Prisma.TripUncheckedCreateWithoutBudgetsInput>
}

export type TripUpsertWithoutBudgetsInput = {
  update: Prisma.XOR<Prisma.TripUpdateWithoutBudgetsInput, Prisma.TripUncheckedUpdateWithoutBudgetsInput>
  create: Prisma.XOR<Prisma.TripCreateWithoutBudgetsInput, Prisma.TripUncheckedCreateWithoutBudgetsInput>
  where?: Prisma.TripWhereInput
}

export type TripUpdateToOneWithWhereWithoutBudgetsInput = {
  where?: Prisma.TripWhereInput
  data: Prisma.XOR<Prisma.TripUpdateWithoutBudgetsInput, Prisma.TripUncheckedUpdateWithoutBudgetsInput>
}

export type TripUpdateWithoutBudgetsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTripsNestedInput
  stops?: Prisma.StopUpdateManyWithoutTripNestedInput
  packingItems?: Prisma.PackingItemUpdateManyWithoutTripNestedInput
  notes?: Prisma.NoteUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateWithoutBudgetsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stops?: Prisma.StopUncheckedUpdateManyWithoutTripNestedInput
  packingItems?: Prisma.PackingItemUncheckedUpdateManyWithoutTripNestedInput
  notes?: Prisma.NoteUncheckedUpdateManyWithoutTripNestedInput
}

export type TripCreateWithoutPackingItemsInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTripsInput
  stops?: Prisma.StopCreateNestedManyWithoutTripInput
  budgets?: Prisma.BudgetCreateNestedManyWithoutTripInput
  notes?: Prisma.NoteCreateNestedManyWithoutTripInput
}

export type TripUncheckedCreateWithoutPackingItemsInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  stops?: Prisma.StopUncheckedCreateNestedManyWithoutTripInput
  budgets?: Prisma.BudgetUncheckedCreateNestedManyWithoutTripInput
  notes?: Prisma.NoteUncheckedCreateNestedManyWithoutTripInput
}

export type TripCreateOrConnectWithoutPackingItemsInput = {
  where: Prisma.TripWhereUniqueInput
  create: Prisma.XOR<Prisma.TripCreateWithoutPackingItemsInput, Prisma.TripUncheckedCreateWithoutPackingItemsInput>
}

export type TripUpsertWithoutPackingItemsInput = {
  update: Prisma.XOR<Prisma.TripUpdateWithoutPackingItemsInput, Prisma.TripUncheckedUpdateWithoutPackingItemsInput>
  create: Prisma.XOR<Prisma.TripCreateWithoutPackingItemsInput, Prisma.TripUncheckedCreateWithoutPackingItemsInput>
  where?: Prisma.TripWhereInput
}

export type TripUpdateToOneWithWhereWithoutPackingItemsInput = {
  where?: Prisma.TripWhereInput
  data: Prisma.XOR<Prisma.TripUpdateWithoutPackingItemsInput, Prisma.TripUncheckedUpdateWithoutPackingItemsInput>
}

export type TripUpdateWithoutPackingItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTripsNestedInput
  stops?: Prisma.StopUpdateManyWithoutTripNestedInput
  budgets?: Prisma.BudgetUpdateManyWithoutTripNestedInput
  notes?: Prisma.NoteUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateWithoutPackingItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stops?: Prisma.StopUncheckedUpdateManyWithoutTripNestedInput
  budgets?: Prisma.BudgetUncheckedUpdateManyWithoutTripNestedInput
  notes?: Prisma.NoteUncheckedUpdateManyWithoutTripNestedInput
}

export type TripCreateWithoutNotesInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTripsInput
  stops?: Prisma.StopCreateNestedManyWithoutTripInput
  budgets?: Prisma.BudgetCreateNestedManyWithoutTripInput
  packingItems?: Prisma.PackingItemCreateNestedManyWithoutTripInput
}

export type TripUncheckedCreateWithoutNotesInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  userId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  stops?: Prisma.StopUncheckedCreateNestedManyWithoutTripInput
  budgets?: Prisma.BudgetUncheckedCreateNestedManyWithoutTripInput
  packingItems?: Prisma.PackingItemUncheckedCreateNestedManyWithoutTripInput
}

export type TripCreateOrConnectWithoutNotesInput = {
  where: Prisma.TripWhereUniqueInput
  create: Prisma.XOR<Prisma.TripCreateWithoutNotesInput, Prisma.TripUncheckedCreateWithoutNotesInput>
}

export type TripUpsertWithoutNotesInput = {
  update: Prisma.XOR<Prisma.TripUpdateWithoutNotesInput, Prisma.TripUncheckedUpdateWithoutNotesInput>
  create: Prisma.XOR<Prisma.TripCreateWithoutNotesInput, Prisma.TripUncheckedCreateWithoutNotesInput>
  where?: Prisma.TripWhereInput
}

export type TripUpdateToOneWithWhereWithoutNotesInput = {
  where?: Prisma.TripWhereInput
  data: Prisma.XOR<Prisma.TripUpdateWithoutNotesInput, Prisma.TripUncheckedUpdateWithoutNotesInput>
}

export type TripUpdateWithoutNotesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTripsNestedInput
  stops?: Prisma.StopUpdateManyWithoutTripNestedInput
  budgets?: Prisma.BudgetUpdateManyWithoutTripNestedInput
  packingItems?: Prisma.PackingItemUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateWithoutNotesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stops?: Prisma.StopUncheckedUpdateManyWithoutTripNestedInput
  budgets?: Prisma.BudgetUncheckedUpdateManyWithoutTripNestedInput
  packingItems?: Prisma.PackingItemUncheckedUpdateManyWithoutTripNestedInput
}

export type TripCreateManyUserInput = {
  id?: string
  name: string
  description?: string | null
  startDate: Date | string
  endDate: Date | string
  coverPhoto?: string | null
  isPublic?: boolean
  publicId?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TripUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stops?: Prisma.StopUpdateManyWithoutTripNestedInput
  budgets?: Prisma.BudgetUpdateManyWithoutTripNestedInput
  packingItems?: Prisma.PackingItemUpdateManyWithoutTripNestedInput
  notes?: Prisma.NoteUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stops?: Prisma.StopUncheckedUpdateManyWithoutTripNestedInput
  budgets?: Prisma.BudgetUncheckedUpdateManyWithoutTripNestedInput
  packingItems?: Prisma.PackingItemUncheckedUpdateManyWithoutTripNestedInput
  notes?: Prisma.NoteUncheckedUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  coverPhoto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TripCountOutputType
 */

export type TripCountOutputType = {
  stops: number
  budgets: number
  packingItems: number
  notes: number
}

export type TripCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  stops?: boolean | TripCountOutputTypeCountStopsArgs
  budgets?: boolean | TripCountOutputTypeCountBudgetsArgs
  packingItems?: boolean | TripCountOutputTypeCountPackingItemsArgs
  notes?: boolean | TripCountOutputTypeCountNotesArgs
}

/**
 * TripCountOutputType without action
 */
export type TripCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripCountOutputType
   */
  select?: Prisma.TripCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TripCountOutputType without action
 */
export type TripCountOutputTypeCountStopsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StopWhereInput
}

/**
 * TripCountOutputType without action
 */
export type TripCountOutputTypeCountBudgetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BudgetWhereInput
}

/**
 * TripCountOutputType without action
 */
export type TripCountOutputTypeCountPackingItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PackingItemWhereInput
}

/**
 * TripCountOutputType without action
 */
export type TripCountOutputTypeCountNotesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NoteWhereInput
}


export type TripSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  startDate?: boolean
  endDate?: boolean
  coverPhoto?: boolean
  isPublic?: boolean
  publicId?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  stops?: boolean | Prisma.Trip$stopsArgs<ExtArgs>
  budgets?: boolean | Prisma.Trip$budgetsArgs<ExtArgs>
  packingItems?: boolean | Prisma.Trip$packingItemsArgs<ExtArgs>
  notes?: boolean | Prisma.Trip$notesArgs<ExtArgs>
  _count?: boolean | Prisma.TripCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["trip"]>

export type TripSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  startDate?: boolean
  endDate?: boolean
  coverPhoto?: boolean
  isPublic?: boolean
  publicId?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["trip"]>

export type TripSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  startDate?: boolean
  endDate?: boolean
  coverPhoto?: boolean
  isPublic?: boolean
  publicId?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["trip"]>

export type TripSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  startDate?: boolean
  endDate?: boolean
  coverPhoto?: boolean
  isPublic?: boolean
  publicId?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TripOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "startDate" | "endDate" | "coverPhoto" | "isPublic" | "publicId" | "userId" | "createdAt" | "updatedAt", ExtArgs["result"]["trip"]>
export type TripInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  stops?: boolean | Prisma.Trip$stopsArgs<ExtArgs>
  budgets?: boolean | Prisma.Trip$budgetsArgs<ExtArgs>
  packingItems?: boolean | Prisma.Trip$packingItemsArgs<ExtArgs>
  notes?: boolean | Prisma.Trip$notesArgs<ExtArgs>
  _count?: boolean | Prisma.TripCountOutputTypeDefaultArgs<ExtArgs>
}
export type TripIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TripIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $TripPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Trip"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    stops: Prisma.$StopPayload<ExtArgs>[]
    budgets: Prisma.$BudgetPayload<ExtArgs>[]
    packingItems: Prisma.$PackingItemPayload<ExtArgs>[]
    notes: Prisma.$NotePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    startDate: Date
    endDate: Date
    coverPhoto: string | null
    isPublic: boolean
    publicId: string
    userId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["trip"]>
  composites: {}
}

export type TripGetPayload<S extends boolean | null | undefined | TripDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TripPayload, S>

export type TripCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TripFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TripCountAggregateInputType | true
  }

export interface TripDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Trip'], meta: { name: 'Trip' } }
  /**
   * Find zero or one Trip that matches the filter.
   * @param {TripFindUniqueArgs} args - Arguments to find a Trip
   * @example
   * // Get one Trip
   * const trip = await prisma.trip.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TripFindUniqueArgs>(args: Prisma.SelectSubset<T, TripFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Trip that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TripFindUniqueOrThrowArgs} args - Arguments to find a Trip
   * @example
   * // Get one Trip
   * const trip = await prisma.trip.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TripFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TripFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Trip that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripFindFirstArgs} args - Arguments to find a Trip
   * @example
   * // Get one Trip
   * const trip = await prisma.trip.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TripFindFirstArgs>(args?: Prisma.SelectSubset<T, TripFindFirstArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Trip that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripFindFirstOrThrowArgs} args - Arguments to find a Trip
   * @example
   * // Get one Trip
   * const trip = await prisma.trip.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TripFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TripFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Trips that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Trips
   * const trips = await prisma.trip.findMany()
   * 
   * // Get first 10 Trips
   * const trips = await prisma.trip.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tripWithIdOnly = await prisma.trip.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TripFindManyArgs>(args?: Prisma.SelectSubset<T, TripFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Trip.
   * @param {TripCreateArgs} args - Arguments to create a Trip.
   * @example
   * // Create one Trip
   * const Trip = await prisma.trip.create({
   *   data: {
   *     // ... data to create a Trip
   *   }
   * })
   * 
   */
  create<T extends TripCreateArgs>(args: Prisma.SelectSubset<T, TripCreateArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Trips.
   * @param {TripCreateManyArgs} args - Arguments to create many Trips.
   * @example
   * // Create many Trips
   * const trip = await prisma.trip.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TripCreateManyArgs>(args?: Prisma.SelectSubset<T, TripCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Trips and returns the data saved in the database.
   * @param {TripCreateManyAndReturnArgs} args - Arguments to create many Trips.
   * @example
   * // Create many Trips
   * const trip = await prisma.trip.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Trips and only return the `id`
   * const tripWithIdOnly = await prisma.trip.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TripCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TripCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Trip.
   * @param {TripDeleteArgs} args - Arguments to delete one Trip.
   * @example
   * // Delete one Trip
   * const Trip = await prisma.trip.delete({
   *   where: {
   *     // ... filter to delete one Trip
   *   }
   * })
   * 
   */
  delete<T extends TripDeleteArgs>(args: Prisma.SelectSubset<T, TripDeleteArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Trip.
   * @param {TripUpdateArgs} args - Arguments to update one Trip.
   * @example
   * // Update one Trip
   * const trip = await prisma.trip.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TripUpdateArgs>(args: Prisma.SelectSubset<T, TripUpdateArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Trips.
   * @param {TripDeleteManyArgs} args - Arguments to filter Trips to delete.
   * @example
   * // Delete a few Trips
   * const { count } = await prisma.trip.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TripDeleteManyArgs>(args?: Prisma.SelectSubset<T, TripDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Trips.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Trips
   * const trip = await prisma.trip.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TripUpdateManyArgs>(args: Prisma.SelectSubset<T, TripUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Trips and returns the data updated in the database.
   * @param {TripUpdateManyAndReturnArgs} args - Arguments to update many Trips.
   * @example
   * // Update many Trips
   * const trip = await prisma.trip.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Trips and only return the `id`
   * const tripWithIdOnly = await prisma.trip.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TripUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TripUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Trip.
   * @param {TripUpsertArgs} args - Arguments to update or create a Trip.
   * @example
   * // Update or create a Trip
   * const trip = await prisma.trip.upsert({
   *   create: {
   *     // ... data to create a Trip
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Trip we want to update
   *   }
   * })
   */
  upsert<T extends TripUpsertArgs>(args: Prisma.SelectSubset<T, TripUpsertArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Trips.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripCountArgs} args - Arguments to filter Trips to count.
   * @example
   * // Count the number of Trips
   * const count = await prisma.trip.count({
   *   where: {
   *     // ... the filter for the Trips we want to count
   *   }
   * })
  **/
  count<T extends TripCountArgs>(
    args?: Prisma.Subset<T, TripCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TripCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Trip.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TripAggregateArgs>(args: Prisma.Subset<T, TripAggregateArgs>): Prisma.PrismaPromise<GetTripAggregateType<T>>

  /**
   * Group by Trip.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TripGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TripGroupByArgs['orderBy'] }
      : { orderBy?: TripGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TripGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTripGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Trip model
 */
readonly fields: TripFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Trip.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TripClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  stops<T extends Prisma.Trip$stopsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Trip$stopsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StopPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  budgets<T extends Prisma.Trip$budgetsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Trip$budgetsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BudgetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  packingItems<T extends Prisma.Trip$packingItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Trip$packingItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackingItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  notes<T extends Prisma.Trip$notesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Trip$notesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Trip model
 */
export interface TripFieldRefs {
  readonly id: Prisma.FieldRef<"Trip", 'String'>
  readonly name: Prisma.FieldRef<"Trip", 'String'>
  readonly description: Prisma.FieldRef<"Trip", 'String'>
  readonly startDate: Prisma.FieldRef<"Trip", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"Trip", 'DateTime'>
  readonly coverPhoto: Prisma.FieldRef<"Trip", 'String'>
  readonly isPublic: Prisma.FieldRef<"Trip", 'Boolean'>
  readonly publicId: Prisma.FieldRef<"Trip", 'String'>
  readonly userId: Prisma.FieldRef<"Trip", 'String'>
  readonly createdAt: Prisma.FieldRef<"Trip", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Trip", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Trip findUnique
 */
export type TripFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * Filter, which Trip to fetch.
   */
  where: Prisma.TripWhereUniqueInput
}

/**
 * Trip findUniqueOrThrow
 */
export type TripFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * Filter, which Trip to fetch.
   */
  where: Prisma.TripWhereUniqueInput
}

/**
 * Trip findFirst
 */
export type TripFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * Filter, which Trip to fetch.
   */
  where?: Prisma.TripWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Trips to fetch.
   */
  orderBy?: Prisma.TripOrderByWithRelationInput | Prisma.TripOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Trips.
   */
  cursor?: Prisma.TripWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Trips from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Trips.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Trips.
   */
  distinct?: Prisma.TripScalarFieldEnum | Prisma.TripScalarFieldEnum[]
}

/**
 * Trip findFirstOrThrow
 */
export type TripFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * Filter, which Trip to fetch.
   */
  where?: Prisma.TripWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Trips to fetch.
   */
  orderBy?: Prisma.TripOrderByWithRelationInput | Prisma.TripOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Trips.
   */
  cursor?: Prisma.TripWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Trips from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Trips.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Trips.
   */
  distinct?: Prisma.TripScalarFieldEnum | Prisma.TripScalarFieldEnum[]
}

/**
 * Trip findMany
 */
export type TripFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * Filter, which Trips to fetch.
   */
  where?: Prisma.TripWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Trips to fetch.
   */
  orderBy?: Prisma.TripOrderByWithRelationInput | Prisma.TripOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Trips.
   */
  cursor?: Prisma.TripWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Trips from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Trips.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Trips.
   */
  distinct?: Prisma.TripScalarFieldEnum | Prisma.TripScalarFieldEnum[]
}

/**
 * Trip create
 */
export type TripCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * The data needed to create a Trip.
   */
  data: Prisma.XOR<Prisma.TripCreateInput, Prisma.TripUncheckedCreateInput>
}

/**
 * Trip createMany
 */
export type TripCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Trips.
   */
  data: Prisma.TripCreateManyInput | Prisma.TripCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Trip createManyAndReturn
 */
export type TripCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * The data used to create many Trips.
   */
  data: Prisma.TripCreateManyInput | Prisma.TripCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Trip update
 */
export type TripUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * The data needed to update a Trip.
   */
  data: Prisma.XOR<Prisma.TripUpdateInput, Prisma.TripUncheckedUpdateInput>
  /**
   * Choose, which Trip to update.
   */
  where: Prisma.TripWhereUniqueInput
}

/**
 * Trip updateMany
 */
export type TripUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Trips.
   */
  data: Prisma.XOR<Prisma.TripUpdateManyMutationInput, Prisma.TripUncheckedUpdateManyInput>
  /**
   * Filter which Trips to update
   */
  where?: Prisma.TripWhereInput
  /**
   * Limit how many Trips to update.
   */
  limit?: number
}

/**
 * Trip updateManyAndReturn
 */
export type TripUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * The data used to update Trips.
   */
  data: Prisma.XOR<Prisma.TripUpdateManyMutationInput, Prisma.TripUncheckedUpdateManyInput>
  /**
   * Filter which Trips to update
   */
  where?: Prisma.TripWhereInput
  /**
   * Limit how many Trips to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Trip upsert
 */
export type TripUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * The filter to search for the Trip to update in case it exists.
   */
  where: Prisma.TripWhereUniqueInput
  /**
   * In case the Trip found by the `where` argument doesn't exist, create a new Trip with this data.
   */
  create: Prisma.XOR<Prisma.TripCreateInput, Prisma.TripUncheckedCreateInput>
  /**
   * In case the Trip was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TripUpdateInput, Prisma.TripUncheckedUpdateInput>
}

/**
 * Trip delete
 */
export type TripDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * Filter which Trip to delete.
   */
  where: Prisma.TripWhereUniqueInput
}

/**
 * Trip deleteMany
 */
export type TripDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Trips to delete
   */
  where?: Prisma.TripWhereInput
  /**
   * Limit how many Trips to delete.
   */
  limit?: number
}

/**
 * Trip.stops
 */
export type Trip$stopsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stop
   */
  select?: Prisma.StopSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stop
   */
  omit?: Prisma.StopOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StopInclude<ExtArgs> | null
  where?: Prisma.StopWhereInput
  orderBy?: Prisma.StopOrderByWithRelationInput | Prisma.StopOrderByWithRelationInput[]
  cursor?: Prisma.StopWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StopScalarFieldEnum | Prisma.StopScalarFieldEnum[]
}

/**
 * Trip.budgets
 */
export type Trip$budgetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Budget
   */
  select?: Prisma.BudgetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Budget
   */
  omit?: Prisma.BudgetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetInclude<ExtArgs> | null
  where?: Prisma.BudgetWhereInput
  orderBy?: Prisma.BudgetOrderByWithRelationInput | Prisma.BudgetOrderByWithRelationInput[]
  cursor?: Prisma.BudgetWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BudgetScalarFieldEnum | Prisma.BudgetScalarFieldEnum[]
}

/**
 * Trip.packingItems
 */
export type Trip$packingItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackingItem
   */
  select?: Prisma.PackingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackingItem
   */
  omit?: Prisma.PackingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackingItemInclude<ExtArgs> | null
  where?: Prisma.PackingItemWhereInput
  orderBy?: Prisma.PackingItemOrderByWithRelationInput | Prisma.PackingItemOrderByWithRelationInput[]
  cursor?: Prisma.PackingItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PackingItemScalarFieldEnum | Prisma.PackingItemScalarFieldEnum[]
}

/**
 * Trip.notes
 */
export type Trip$notesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Note
   */
  select?: Prisma.NoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Note
   */
  omit?: Prisma.NoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoteInclude<ExtArgs> | null
  where?: Prisma.NoteWhereInput
  orderBy?: Prisma.NoteOrderByWithRelationInput | Prisma.NoteOrderByWithRelationInput[]
  cursor?: Prisma.NoteWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NoteScalarFieldEnum | Prisma.NoteScalarFieldEnum[]
}

/**
 * Trip without action
 */
export type TripDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
}
